Repository geoserver/geoserver, pull requests merged in 2022-08, with the labels that each got.

#6091 [GEOS-10609] Fix Issue retrieving a workspace style without prefix on JDBCConfig
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
  src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
Labels: backport 2.20.x, backport 2.21.x

#6109 [GEOS-10620] Update oshi to 6.2.2 to support Apple M2 CPU
  src/pom.xml
Labels: dependencies, backport 2.20.x, backport 2.21.x

#6090 [GEOS-10607] Links disappearing for the Admin user
  src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
  src/main/src/test/java/org/geoserver/security/impl/DefaultResourceAccessManagerTest.java
  src/web/core/src/main/java/org/geoserver/web/WorkspaceAdminComponentAuthorizer.java
Labels: backport 2.20.x, backport 2.21.x

#6107 [GEOS-10618] DOCS: Official GeoServer Docker Image (GSIP-192)
  doc/en/user/source/installation/docker.rst
  doc/en/user/source/installation/index.rst
Labels: backport 2.21.x

#6128 [GEOS-10629] Features Templating - Allow control over encodign of complex attribute with n cardinality - [GEOS-10630] SchemalessFeatures - POST filter might not get evaluted
  doc/en/user/source/community/features-templating/directives.rst
  src/community/features-templating/features-templating-core/pom.xml
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/TemplateCQLManager.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/AggregateFunction.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/AggregateOpFactory.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/AggregationOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/AvgOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/FilteringFunction.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/JoinOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/MaxOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/MinMaxOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/MinOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/SortFunction.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/StreamFunction.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/StringCQLFunction.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/expressions/aggregate/UniqueOp.java
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
  src/community/features-templating/features-templating-core/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/expressions/AggregateFunctionTest.java
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/expressions/FilteringFunctionTest.java
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/expressions/ListFunctionsTestSupport.java
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/expressions/SortFunctionTest.java
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/expressions/StreamFunctionTest.java
  src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/MappedFeatureStreamFun.json
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetComplexFeaturesResponseWFSTest.java
  src/community/schemaless-features/mongodb-schemaless/pom.xml
  src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoSchemalessFeatureSource.java
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/SchemalessCollectionTest.java
Labels: backport 2.20.x, backport 2.21.x

#6129 [GEOS-10631] AccessManager will not be looked up if multiple beans are of type DefaultResourceAccessManager
  src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
  src/main/src/test/java/org/geoserver/security/impl/ResourceAccessManagerLookupTest.java
Labels: backport 2.20.x, backport 2.21.x

#6115 [GEOS-10547] Integrated WMS caching without the tiled parameter might…
  src/gwc/src/main/java/org/geoserver/gwc/wms/CachingWebMapService.java
  src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
  src/gwc/src/test/java/org/geoserver/gwc/PassThroughMethodInvocation.java
Labels: backport 2.20.x, backport 2.21.x

#6125 [GEOS-10628] GWC Environment parameterization does not work on geoserver startup
  src/gwc/src/main/java/org/geoserver/gwc/GWC.java
  src/gwc/src/test/java/org/geoserver/gwc/GWCTest.java
Labels: backport 2.20.x, backport 2.21.x

#6149 [GEOS-10598] XSS vulnerability in the email address field - fix too eager escape
  src/pom.xml
  src/web/core/src/main/java/org/geoserver/web/GeoServerHomePage.java
  src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/WMSStoreNewPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/WMTSStoreNewPageTest.java
Labels: backport 2.20.x, backport 2.21.x
