Repository geoserver/geoserver, pull requests merged in 2022-07, with the labels that each got.

#5971 [GEOS-10551] Refactor commons-httpclient usage in the WPS module
  src/extension/wps/wps-core/pom.xml
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/RemoteRequestInputProvider.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/executor/RemoteRequestInputProviderTest.java
  src/extension/wps/wps-core/src/test/resources/org/geoserver/wps/executor/foo.txt
  src/extension/wps/wps-core/src/test/resources/org/geoserver/wps/executor/foo.zip
  src/extension/wps/wps-core/src/test/resources/org/geoserver/wps/executor/test.txt
  src/extension/wps/wps-core/src/test/resources/org/geoserver/wps/executor/test.zip
Labels: backport 2.20.x, backport 2.21.x

#6015 [GEOS-10539] DescribeLayer typeName is no longer workspace qualified
  src/wms/src/main/java/org/geoserver/wms/describelayer/DescribeLayerTransformer.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DescribeLayerTest.java
Labels: backport 2.20.x, backport 2.21.x

#6035 [GEOS-10579] Bump oshi-core from 6.2.0 to 6.2.1
  src/pom.xml
Labels: backport 2.20.x, backport 2.21.x

#6016 [GEOS-10570] Deleting a style in a Hazelcast cluster renames the styles directory
  src/main/src/main/java/org/geoserver/config/GeoServerResourcePersister.java
  src/main/src/test/java/org/geoserver/config/GeoServerPersistersTest.java
Labels: backport 2.20.x, backport 2.21.x

#6057 [GEOS-10584] Do not close origional inputstream when logging request body
  src/main/src/main/java/org/geoserver/filters/BufferedRequestStream.java
  src/main/src/main/java/org/geoserver/filters/BufferedRequestWrapper.java
  src/main/src/main/java/org/geoserver/filters/LoggingFilter.java
  src/main/src/test/java/org/geoserver/filters/BufferedRequestStreamTest.java
  src/main/src/test/java/org/geoserver/filters/LoggingFilterTest.java
Labels: backport 2.20.x, backport 2.21.x

#6056 [GEOS-10585] Upgrade to Jetty from 9.4.44 to 9.4.48
  src/pom.xml
Labels: dependencies, backport 2.21.x

#6059 Bump org.owasp:dependency-check-maven from 7.0.4 to 7.1.1
  src/pom.xml
Labels: backport 2.21.x

#6065 [GEOS-10588] avoid community profiles duplicating modules
  src/community/pom.xml
  src/community/security/oauth2/pom.xml
  src/community/security/pom.xml
Labels: backport 2.20.x, backport 2.21.x
