Repository geoserver/geoserver, pull requests merged in 2022-10, with the labels that each got.

#6210 [GEOS-10680] FidTransformeVisitor misspelled
  src/main/src/main/java/org/geoserver/feature/retype/FidTransformerVisitor.java
  src/main/src/main/java/org/geoserver/feature/retype/RetypingDataStore.java
Labels: backport 2.20.x, backport 2.21.x

#6205 [GEOS-10677] Improve cleanup of multi part form upload to the dispatcher
  src/main/src/main/java/applicationContext.xml
  src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
  src/ows/src/main/java/org/geoserver/ows/FileItemCleanupCallback.java
  src/ows/src/test/java/org/geoserver/ows/FileItemCleanupCallbackTest.java
  src/ows/src/test/java/org/geoserver/ows/applicationContext.xml
  src/pom.xml
Labels: backport 2.20.x, backport 2.21.x

#6226 [GEOS-10699] WCS 2.0 latitude subsetting may fail if the source data has longitudes spanning both datelines
  src/wcs2_0/src/main/java/org/geoserver/wcs2_0/WCSEnvelope.java
  src/wcs2_0/src/test/java/org/geoserver/wcs2_0/WCSEnvelopeTest.java
Labels: backport 2.20.x, backport 2.21.x

#6225 [GEOS-10698] - OGCAPI and REST API coexistence issue
  src/community/ogcapi/ogcapi-core/pom.xml
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIConfigurationSupport.java
  src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/ApiConfigurationSupportTest.java
Labels: backport 2.21.x, backport 2.22.x

#6230 [GEOS-10696] Allow configuration of Output Format types allowed in GetFeature
  doc/en/user/source/services/wfs/img/services_WFS_outputformat.png
  doc/en/user/source/services/wfs/webadmin.rst
  src/community/rest-openapi/openapi/src/main/resources/org/geoserver/rest/openapi/1.0.0/config.yaml
  src/community/rest-openapi/openapi/src/main/resources/org/geoserver/rest/openapi/1.0.0/owsservices.yaml
  src/web/wfs/src/main/java/org/geoserver/wfs/web/OutputTypesFormComponent.html
  src/web/wfs/src/main/java/org/geoserver/wfs/web/OutputTypesFormComponent.java
  src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSAdminPage.html
  src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSAdminPage.java
  src/web/wfs/src/main/resources/GeoServerApplication.properties
  src/web/wfs/src/test/java/org/geoserver/wfs/web/WFSAdminPageTest.java
  src/wfs/src/main/java/applicationContext.xml
  src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java
  src/wfs/src/main/java/org/geoserver/wfs/WFSInfo.java
  src/wfs/src/main/java/org/geoserver/wfs/WFSInfoImpl.java
  src/wfs/src/main/java/org/geoserver/wfs/WFSXStreamLoader.java
  src/wfs/src/main/java/org/geoserver/wfs/outputformat/WFSOutputFormatCallback.java
  src/wfs/src/test/java/org/geoserver/wfs/GetCapabilitiesTest.java
  src/wfs/src/test/java/org/geoserver/wfs/outputformat/WFSOutputFormatCallbackTest.java
Labels: backport 2.22.x

#6243 Bump org.apache.commons:commons-text from 1.9 to 1.10.0
  src/pom.xml
Labels: dependencies, backport 2.20.x, backport 2.21.x, backport 2.22.x

#6246 add note on how to add a custom layer to the developer manual
  doc/en/developer/source/programming-guide/testing/index.rst
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6245 Update Ubuntu 18.04 workflows to 20.04
  .github/workflows/backport.yml
  .github/workflows/linux_jdk8.yml
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6254 [GEOS-10700] Restore ability to customize built-in logging profiles along with profile update procedure
  doc/en/user/source/configuration/logging.rst
  src/main/src/main/java/org/geoserver/logging/LoggingStartupContextListener.java
  src/main/src/main/java/org/geoserver/logging/LoggingUtils.java
  src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java
  src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
Labels: backport 2.21.x, backport 2.22.x

#6259 [GEOS-10709] Schemaless Features - Simplified property access might return values for wrong property names
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/SchemalessCollectionTest.java
  src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/filter/SchemalessPropertyAccessorFactory.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6265 [GEOS-10711] ConcurrentModificationException can happen while modifying data access rules with concurrent WMS traffic
  src/main/src/main/java/org/geoserver/security/SecuredResourceNameChangeListener.java
  src/main/src/main/java/org/geoserver/security/impl/AbstractAccessRuleDAO.java
  src/main/src/main/java/org/geoserver/security/impl/DataAccessRule.java
  src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java
  src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
  src/main/src/main/java/org/geoserver/security/impl/RESTAccessRuleDAO.java
  src/main/src/main/java/org/geoserver/security/impl/ServiceAccessRuleDAO.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAccesRuleDAOConcurrencyTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/DataAccesRuleDAOConcurrencyTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/RESTAccessRuleDAOTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/ServiceAccessRuleDAOTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6282 [GEOS-10647] Welcome page links to GetCapabilities do not follow the OGC standards
  src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
  src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCServiceLinksTest.java
Labels: backport 2.22.x

#6280 [GEOS-10715] - Workspace Filter for PublishedInfo does not include LayerGroups
  src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
Labels: backport 2.22.x

#6237 Update GeoServerApplication_zh_CN.utf8.properties
  src/web/security/core/src/main/resources/GeoServerApplication_zh_CN.utf8.properties
Labels: backport 2.22.x

#6284 GEOS-10717: XStreamServiceLoader performance improvement with XstreamPersister caching
  src/main/src/main/java/org/geoserver/config/util/XStreamServiceLoader.java
  src/main/src/test/java/org/geoserver/config/util/XStreamServiceLoaderTest.java
Labels: backport 2.21.x, backport 2.22.x

#6289 [Fixes GEOS-10718] the OIDC plugin does not currently take into account the id_token_hint parameter
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6308 [GEOS-4727] Editing SQL views seems to be leaking connections
  src/web/core/pom.xml
  src/web/core/src/main/java/org/geoserver/web/data/layer/SQLViewAbstractPage.java
  src/web/core/src/test/java/org/geoserver/web/data/layer/SqlViewEditPageTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x
