Repository geoserver/geoserver, pull requests merged in 2022-06, with the labels that each got.

#5917 [GEOS-10522] RestControllerAdvice report exception with null message
  src/platform/src/main/java/org/geoserver/platform/resource/FileSystemWatcher.java
  src/rest/src/main/java/org/geoserver/rest/RestControllerAdvice.java
  src/rest/src/test/java/org/geoserver/rest/ExceptionHandlingTest.java
  src/rest/src/test/java/org/geoserver/rest/ExceptionThrowingController.java
Labels: backport needed

#5923 Adding backport bot from https://github.com/tibdex/backport
  .github/workflows/backport.yml
Labels: backport 2.20.x, backport 2.21.x

#5925 Adding backport bot (same version used by QGIS)
  .github/workflows/backport.yml
Labels: backport 2.20.x, backport 2.21.x

#5906 [GEOS-10518] Partial RELINQUISH_LOG4J_CONTROL regression with WildFly
  src/main/src/main/java/org/geoserver/logging/LoggingUtils.java
  src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java
Labels: backport 2.21.x

#5890 [GEOS-10487] Log4J custom logging XML configuration is case-insenstive
  src/main/src/main/java/org/geoserver/logging/GeoServerXMLConfiguration.java
  src/main/src/test/java/org/geoserver/logging/LoggingStartupContextListenerTest.java
Labels: backport 2.21.x

#5935 [GEOS-10534] a badly formed delete transaction will get a NPE instead of an informative error message
  src/wfs/src/main/java/org/geoserver/wfs/DeleteElementHandler.java
  src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
Labels: backport 2.20.x, backport 2.21.x

#5946 [GEOS-10513] Coverage API Temporal Problems With Input and Retrieval
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/CoveragesService.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/DomainSetBuilder.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/TimeDimensionHelper.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/GeneralGrid.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/IndexAxis.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/IrregularAxis.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/coverages/cis/RegularAxis.java
  src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/coverages/collection_include.ftl
  src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CollectionTest.java
  src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoverageTest.java
  src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/CoveragesTestSupport.java
  src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/coverages/DomainSetTest.java
Labels: backport 2.21.x

#5810 [GEOS-4613] - Expose more JVM statistics on the web gui
  src/web/core/src/main/java/org/geoserver/web/admin/AbstractStatusPage.java
  src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java
  src/web/core/src/main/java/org/geoserver/web/system/status/JVMConsolePanel.html
  src/web/core/src/main/java/org/geoserver/web/system/status/JVMConsolePanel.java
  src/web/core/src/main/resources/GeoServerApplication.properties
  src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java
  src/web/core/src/test/java/org/geoserver/web/system/status/JVMConsolePanelTest.java
Labels: backport 2.20.x, backport 2.21.x

#5922 [GEOS-10528] Empty groupList tag remains after group deletion
  src/main/src/main/java/org/geoserver/security/impl/AbstractRoleStore.java
  src/security/security-tests/src/test/java/org/geoserver/security/xml/XMLRoleServiceTest.java
Labels: backport 2.20.x, backport 2.21.x

#5985 [GEOS-10545] Layer Group cache not initialized
  src/extension/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
  src/extension/geofence/src/main/resources/applicationContext.xml
  src/main/pom.xml
  src/main/src/main/java/applicationContext.xml
  src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
  src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
  src/main/src/main/java/org/geoserver/security/impl/LayerGroupContainmentCache.java
  src/main/src/test/java/org/geoserver/security/impl/LayerGroupContainmentCacheTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplGroupsTest.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapIntegrationTest.java
Labels: backport 2.20.x, backport 2.21.x

#5995 [GEOS-10562] Bump oshi-core from 5.8.6 to 6.2.0
  src/pom.xml
Labels: dependencies, backport 2.20.x, backport 2.21.x

#5996 [Fixes GEOS-10563] XStream persister serializer exception on JMS clustering messages exchange
  src/community/jms-cluster/jms-commons/pom.xml
  src/community/jms-cluster/jms-commons/src/main/java/org/geoserver/cluster/JMSXStreamPersisterInitializer.java
  src/community/jms-cluster/jms-commons/src/main/resources/applicationContext.xml
Labels: backport needed, backport 2.20.x, backport 2.21.x

#5952 [GEOS-10542] Use headers for proxy URL on workspace level
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteTest.java
  src/main/src/main/java/org/geoserver/config/GeoServerInfo.java
  src/main/src/main/java/org/geoserver/config/SettingsInfo.java
  src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
  src/main/src/main/java/org/geoserver/config/impl/SettingsInfoImpl.java
  src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
  src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
  src/main/src/test/java/org/vfny/geoserver/util/ResponseUtilsTest.java
  src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/AdminRequestTest.java
  src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage$SettingsPanel.html
  src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
  src/web/core/src/main/resources/GeoServerApplication.properties
Labels: backport 2.20.x, backport 2.21.x

#6012 [GEOS-10566] Coverage API time range calculation needs to be hardened
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java
  src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/TimeExtentCalculatorTest.java
  src/community/ogcapi/ogcapi-core/src/test/resources/org/geoserver/ogcapi/TimeElevation.properties
  src/community/ogcapi/ogcapi-core/src/test/resources/org/geoserver/ogcapi/TimeElevationEmpty.properties
Labels: backport 2.21.x
