Repository geoserver/geoserver, pull requests merged in 2023-01, with the labels that each got.

#6476 jdbcconfig - add logging of non-encodable property names
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java
Labels: backport 2.21.x, backport 2.22.x

#6475 jdbcconfig - log parameter values in order they appear in query
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbUtils.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java
Labels: backport 2.21.x, backport 2.22.x

#6469 [GEOS-10812] Update Jettison to 1.5.3
  src/pom.xml
Labels: backport 2.21.x, backport 2.22.x

#6467 [GEOS-10794] Add a new vector data source (Web Feature Server (NG)) Filter compliance level bug
  src/web/core/src/main/java/org/geoserver/web/data/store/panel/DropDownChoiceParamPanel.java
  src/web/core/src/test/java/org/geoserver/web/data/store/WFSStoreNewPageTest.java
Labels: backport 2.21.x, backport 2.22.x

#6488 jdbcconfig - make unit tests run faster in IDE
  src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/JDBCConfigTestSupport.java
Labels: backport 2.21.x, backport 2.22.x

#6485 [GEOS-10816] OGC API Features complex features test fails since introduction of <meta> tag in HTML templates
  src/community/gsr/src/test/java/org/geoserver/gsr/controller/ControllerTest.java
  src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/OGCApiTestSupport.java
  src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/features/ComplexFeaturesTest.java
  src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
Labels: backport 2.21.x, backport 2.22.x

#6453 [GEOS-10807] LayerGroup with nested group POST rest op fails with null styles attribute
  src/main/src/main/java/org/geoserver/config/util/XStreamPersister.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/LayerGroupControllerTest.java
Labels: backport 2.21.x, backport 2.22.x

#6481 [GEOS-10814] Update jdbc config to use consistent SQL formatting
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbMappings.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/Dialect.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/FilterToCatalogSQL.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/OracleDialect.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/QueryBuilder.java
  src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/QueryBuilderTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6501 [GEOS-10818] Schemaless Property Accessor returns emptylist instead of null for null/not existing properties
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/SchemalessCollectionTest.java
  src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/filter/SchemalessPropertyAccessorFactory.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6506 [GEOS-10821] OpenID - Allow configuration of post_login_redirect_uri
  doc/en/user/source/community/oauth2/index.rst
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdFilterConfigTest.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanelTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x

#6473 [GEOS-10813] -- jdbcconfig cache bug,changed the workspace name
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
Labels: backport 2.21.x, backport 2.22.x

#6516 [GEOS-10827] Document property selection in image mosaic
  doc/en/user/source/data/raster/imagemosaic/configuration.rst
Labels: backport 2.22.x

#6519 [GEOS-10829] JDBC Config missing some nested layer properties
  src/community/jdbcconfig/src/main/resources/org/geoserver/jdbcconfig/internal/nested_properties.properties
Labels: backport 2.21.x, backport 2.22.x

#6523 jdbcconfig - fixed incorrect logging for queries with complex filters
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbUtils.java
  src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/internal/DbUtilsTest.java
Labels: backport 2.21.x, backport 2.22.x

#6524 jdbcconfig - added debug logging to all database queries
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/ConfigDatabase.java
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/internal/DbMappings.java
Labels: backport 2.21.x, backport 2.22.x

#6543 [GEOS-10828] OGC API - Features - Plugin breaks core /rest API with JSON payloads
  src/community/ogcapi/ogcapi-core/pom.xml
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2HttpMessageConverter.java
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/MappingJackson2YAMLMessageConverter.java
  src/community/ogcapi/ogcapi-core/src/test/java/org/geoserver/ogcapi/ApiConfigurationSupportTest.java
  src/rest/src/main/java/org/geoserver/rest/converters/XStreamJSONMessageConverter.java
  src/rest/src/main/java/org/geoserver/rest/converters/XStreamXMLMessageConverter.java
Labels: backport 2.21.x, backport 2.22.x
