Repository geoserver/geoserver, pull requests merged in 2023-09, with the labels that each got.

#7107 [GEOS-11116] GetMap/GetFeatureInfo with groups and view params can with mismatched layers/params
  src/wms/src/main/java/org/geoserver/wms/map/GetMapKvpRequestReader.java
  src/wms/src/test/java/org/geoserver/wms/map/GetMapKvpRequestReaderTest.java
Labels: backport 2.22.x, backport 2.23.x

#7113 [GEOS-11118] Add Temporal Extents domain and datetime parameter to Maps API
  src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/CollectionDocument.java
  src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java
  src/community/ogcapi/ogcapi-maps/src/main/resources/org/geoserver/ogcapi/v1/maps/collection_include.ftl
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionTest.java
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTestSupport.java
  src/community/ogcapi/ogcapi-maps/src/test/resources/org/geoserver/ogcapi/v1/maps/TimeElevationWithStartEnd.properties
Labels: backport 2.22.x, backport 2.23.x

#7118 [Backport 2.23.x] Bump org.eclipse.jetty:jetty-servlets from 9.4.51.v20230217 to 9.4.52.v20230823 in /src
  src/pom.xml
Labels: dependencies

#7122 [GEOS-11131] Update GeoFence to 3.7-RC
  src/pom.xml
Labels: backport 2.24.x

#7124 [GEOS-11132] Updating printing plugin to mapfish-print-lib 2.3-RC
  src/pom.xml
Labels: backport 2.24.x

#7128 Revert javadoc maven plugin upgrade, add build to ensure aggregate works
  .github/workflows/javadoc.yml
  src/pom.xml
Labels: backport 2.24.x

#7132 [GEOS-11136] Update MapML viewer to latest release 0.12.0
  doc/en/user/source/extensions/mapml/index.rst
  src/extension/mapml/src/main/resources/viewer/widget/DOMTokenList.js
  src/extension/mapml/src/main/resources/viewer/widget/DOMTokenList.js.map
  src/extension/mapml/src/main/resources/viewer/widget/README.md
  src/extension/mapml/src/main/resources/viewer/widget/layer.js
  src/extension/mapml/src/main/resources/viewer/widget/layer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml.css
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js.map
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js.map
Labels: backport 2.24.x

#7115 [GEOS-11122] Loading font from FontCache when specified in legend options.
  src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
  src/wms/src/test/java/org/geoserver/wms/legendgraphic/LegendUtilsTest.java
  src/wms/src/test/resources/org/geoserver/wms/legendgraphic/Anarchist_Mustache.ttf
  src/wms/src/test/resources/org/geoserver/wms/legendgraphic/LICENSE-Anarchist_Mustache.ttf
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x
