Repository geoserver/geoserver, pull requests merged in 2023-04, with the labels that each got.

#6756 Features templating html double escaping fix
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java
  src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/TemplateGetFeatureResponseHelper.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/ComplexGetFeatureInfoTest.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetComplexFeatureResponseTest.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java
  src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6757 [GEOS-10922] Features templating exception on text/plain format
  src/community/features-templating/features-templating-ows/pom.xml
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/TemplateCallback.java
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/HTMLTemplateResponse.java
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/JSONLDGetFeatureResponse.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wfs/WfsGetCapabilitiesTest.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wms/WmsGetCapabilitiesTest.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/wms/WmsGetFeatureInfoTest.java
Labels: backport 2.22.x, backport 2.23.x

#6607 [GEOS-10837] geopackage output fails when java.io.tmpdir on network share
  doc/en/user/source/extensions/geopkg-output/install.rst
  doc/en/user/source/extensions/geopkg-output/usage.rst
  src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java
  src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6766 [GEOS-10859] swagger api update to 4.15.5
  src/community/ogcapi/ogcapi-core/src/main/resources/swagger-ui/oauth2-redirect.html
  src/community/ogcapi/ogcapi-core/src/main/resources/swagger-ui/swagger-ui-bundle.js
  src/community/ogcapi/ogcapi-core/src/main/resources/swagger-ui/swagger-ui-standalone-preset.js
  src/community/ogcapi/ogcapi-core/src/main/resources/swagger-ui/swagger-ui.css
  src/community/ogcapi/ogcapi-core/src/main/resources/swagger-ui/swagger-ui.js
Labels: backport 2.22.x, backport 2.23.x

#6791 [GEOS-10950] Performance regression in DescribeFeatureType across allfeature types
  src/wfs/src/main/java/org/geoserver/wfs/xml/FeatureTypeSchemaBuilder.java
  src/wfs/src/test/java/org/geoserver/wfs/v2_0/DescribeFeatureTypeTest.java
  src/wfs/src/test/java/org/geoserver/wfs/xml/FeatureTypeInfoSchemaBuilderTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6789 Upgrade spring-integration-core:5.0.0 -> 5.5.17
  src/community/backup-restore/core/pom.xml
  src/pom.xml
Labels: backport 2.23.x

#6803 Small fix to docker docs: correction for --mount and --env examples
  doc/en/user/source/installation/docker.rst
Labels: backport 2.22.x, backport 2.23.x

#6799 [GEOS-10946] WMS GetLegendGraphic throws FootprintsTransformation can…
  src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendGraphicBuilder.java
  src/wms/src/test/java/org/geoserver/wms/legendgraphic/LegendLayoutTest.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetLegendGraphicTest.java
  src/wms/src/test/resources/org/geoserver/wms/legendgraphic/footprints.sld
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x
