Repository geoserver/geoserver, pull requests merged in 2023-10, with the labels that each got.

#7143 [GEOS-11138] Add dtd to jetty context file
  src/web/app/src/test/resources/jetty-context.xml
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x

#7102 [GEOS-10850] Root cause in OGC WFS-T errors, when using verbose service exceptions
  src/wfs/src/main/java/org/geoserver/wfs/AbstractTransactionElementHandler.java
  src/wfs/src/main/java/org/geoserver/wfs/DeleteElementHandler.java
  src/wfs/src/main/java/org/geoserver/wfs/InsertElementHandler.java
  src/wfs/src/main/java/org/geoserver/wfs/ReplaceElementHandler.java
  src/wfs/src/main/java/org/geoserver/wfs/Transaction.java
  src/wfs/src/main/java/org/geoserver/wfs/UpdateElementHandler.java
  src/wfs/src/main/java/org/geoserver/wfs/WFSTransactionExceptionFactory.java
  src/wfs/src/test/java/org/geoserver/wfs/ExceptionThrowingTrigger.java
  src/wfs/src/test/java/org/geoserver/wfs/TransactionTest.java
Labels: backport 2.24.x

#7150 [GEOS-11140] WPS download can leak image references in the RasterCleaner
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java
  src/extension/wps-download/src/main/resources/applicationContext.xml
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/RasterCleanerProcessListener.java
  src/extension/wps-download/src/test/resources/TestContext.xml
  src/wms/src/main/java/org/geoserver/wms/RasterCleaner.java
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x

#7165 Resolve geoserverBaseDir maven property using standard means
  src/pom.xml
Labels: backport 2.23.x, backport 2.24.x

#7155 [GEOS-11142] Add mime type mapping for yaml files
  src/web/app/src/main/webapp/WEB-INF/web.xml
Labels: backport 2.23.x, backport 2.24.x

#7179 Weblate integration : remove blocking translations and test adding new translations
  src/community/elasticsearch/src/main/resources/GeoServerApplication_fr.properties
  src/extension/mapml/src/main/resources/GeoServerApplication_fr.properties
  src/web/core/src/main/resources/GeoServerApplication_zh_CN.utf8.properties
  src/web/demo/src/main/resources/GeoServerApplication_zh_CN.utf8.properties
  src/web/gwc/src/main/resources/GeoServerApplication_zh_CN.utf8.properties
  src/web/security/core/src/main/resources/GeoServerApplication_zh_CN.utf8.properties
  src/web/wms/src/main/resources/GeoServerApplication_zh_CN.utf8.properties
Labels: backport 2.24.x

#7186 [GEOS-11134] Confirm community assemble downloads have geoserver-*.zip finalName
  src/community/pom.xml
Labels: backport 2.24.x

#7188 [GEOS-11134] build fix for literal include language markdown reference
  doc/en/developer/source/policies/community-modules.rst
Labels: backport 2.24.x

#7187 [GEOS-11161] Address build warnings for running unit tests
  src/community/security/keycloak/pom.xml
  src/community/security/oauth2-geonode/pom.xml
  src/community/security/oauth2-github/pom.xml
  src/community/security/oauth2-google/pom.xml
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
  src/community/security/oauth2/oauth2-core/pom.xml
  src/pom.xml
Labels: backport 2.23.x, backport 2.24.x

#7198 [GEOS-11166] OGC API Maps HTML representation fail without datetime parameter
  src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java
Labels: backport 2.23.x, backport 2.24.x

#7195 [GEOS-11165] STAC Datacube switch eoSummaries bounds output to individual values
  doc/en/user/source/community/opensearch-eo/STAC.rst
  src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/AggregateFactory.java
  src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/functions/EoSummaries.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/functions/EoSummariesTest.java
  src/community/oseo/oseo-stac/src/test/resources/collections.json
Labels: backport 2.23.x, backport 2.24.x

#7205 Fix build for community module rest-openapi
  src/community/rest-openapi/generated/feign-client/client-api-config.json
  src/community/rest-openapi/generated/feign-client/pom.xml
  src/community/rest-openapi/generated/model/catalog-model-config.json
  src/community/rest-openapi/generated/model/config-model-config.json
  src/community/rest-openapi/generated/model/pom.xml
  src/community/rest-openapi/java-client/docker-compose.yml
  src/community/rest-openapi/java-client/src/main/java/org/geoserver/restconfig/client/GeoServerClient.java
  src/community/rest-openapi/java-client/src/test/java/org/geoserver/restconfig/client/SettingsClientIT.java
  src/community/rest-openapi/openapi/src/main/resources/org/geoserver/rest/openapi/1.0.0/config.yaml
  src/community/rest-openapi/pom.xml
Labels: backport 2.24.x

#7218 [GEOS-11173] Default to using HttpOnly session cookies
  doc/en/user/source/production/config.rst
  src/web/app/src/main/webapp/WEB-INF/web.xml
Labels: backport 2.22.x, backport 2.23.x

#7217 Update CITE docker Tomcat version to use 9-jdk11 as base image
  build/cite/geoserver/Dockerfile
Labels: dependencies

#7073 [GEOS-11101] metadata: multiple tabs
  doc/en/user/source/extensions/metadata/configuration.rst
  doc/en/user/source/extensions/metadata/images/metadata-tabs.png
  doc/en/user/source/extensions/metadata/uiconfiguration.rst
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/AttributeConfiguration.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/MetadataConfiguration.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/AttributeConfigurationImpl.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/MetadataConfigurationImpl.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/service/impl/ConfigurationServiceImpl.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/web/MetadataTemplatePage.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/web/layer/MetadataTabPanel.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/MetadataPanel.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/attribute/AttributeDataProvider.java
  src/extension/metadata/src/test/java/org/geoserver/metadata/AbstractMetadataTest.java
  src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java
  src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-tabs.yaml
  src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x

#7181 [GEOS-11155] Add the X-Content-Type-Options header
  doc/en/user/source/production/config.rst
  src/main/src/main/java/org/geoserver/filters/XFrameOptionsFilter.java
  src/main/src/test/java/org/geoserver/filters/XFrameOptionsFilterTest.java
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x

#7222 [GEOS-11176] Add validation to file wrapper resource paths
  src/platform/src/main/java/org/geoserver/platform/resource/Files.java
  src/platform/src/main/java/org/geoserver/platform/resource/URIs.java
  src/platform/src/test/java/org/geoserver/platform/resource/ResourceTheoryTest.java
Labels: backport 2.23.x, backport 2.24.x
