Repository geoserver/geoserver, pull requests merged in 2023-06, with the labels that each got.

#6872 [GEOS-10993] Disabled resources can cause incorrect CSW GetRecords response
  src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/CatalogStoreFeatureCollection.java
  src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/GetRecordsTest.java
Labels: backport 2.22.x, backport 2.23.x

#6886 [GEOS-11010] Upgrade guava from 30.1 to 32.0.0
  src/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6887 [GEOS-11011] Upgrade postgresql from 42.4.3 to 42.6.0
  src/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6888 [GEOS-11012] Upgrade commons-collections4 from 4.2 to 4.4
  src/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6885 [GEOS-10936] YSLD and OGC API modules are incompatible
  src/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6884 [GEOS-10980] CSS extension lacks ASM JARs as of 2.23.0, stops rendering layer when style references a file
  src/release/ext-css.xml
Labels: backport 2.23.x

#6882 hz-cluster - removed unused cache implementation
  src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzCacheProvider.java
  src/community/hz-cluster/src/main/java/org/geoserver/cluster/hazelcast/HzExtensionFilter.java
  src/community/hz-cluster/src/main/resources/applicationContext.xml
  src/community/hz-cluster/src/test/java/org/geoserver/cluster/hazelcast/HzCacheProviderTest.java
  src/community/hz-cluster/src/test/java/org/geoserver/cluster/hazelcast/HzExtensionFilterTest.java
Labels: backport 2.22.x, backport 2.23.x

#6903 [GEOS-11018] Upgrade commons-lang3 from 3.8.1 to 3.12.0
  src/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6906 [GEOS-11020] Add test scope to mockito-core dependency
  src/community/ogcapi/ogcapi-tiles/pom.xml
  src/extension/csw/web-csw/pom.xml
  src/web/core/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6877 [GEOS-10997] Data Security Layer groups
  src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/AbstractAuthorizationTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/DefaultDataAccessManagerTreeTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/SecureCatalogImplTest.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/complex.properties
Labels: backport 2.23.x

#6917 [GEOS-10968] task manager: fix dependendies for java 11
  src/community/taskmanager/core/pom.xml
  src/community/taskmanager/metadata/pom.xml
  src/community/taskmanager/s3/pom.xml
  src/web/app/pom.xml
Labels: backport 2.22.x, backport 2.23.x

#6869 [GEOS-10994] OOM due to too many dimensions when range requested
  src/main/src/test/java/org/geoserver/data/test/TimeElevation.properties
  src/wms/src/main/java/applicationContext.xml
  src/wms/src/main/java/org/geoserver/wms/GetFeatureInfo.java
  src/wms/src/main/java/org/geoserver/wms/GetMap.java
  src/wms/src/main/java/org/geoserver/wms/WMS.java
  src/wms/src/test/java/org/geoserver/wms/WMSTest.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetFeatureInfoIntegrationTest.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_3/GetMapIntegrationTest.java
Labels: backport 2.22.x, backport 2.23.x

#6921 [GEOS-10931] Taskmanager: copytabletask: drop table in transaction
  src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/CopyTableTaskTypeImpl.java
Labels: backport 2.23.x

#6922 [GEOS-11022] Taskmanager: support isolated catalog facades
  src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/external/ExtTypes.java
  src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/DbLocalPublicationTaskTypeImpl.java
  src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/tasks/FileLocalPublicationTaskTypeImpl.java
Labels: backport 2.23.x

#6927 [GEOS-10931] taskmanager: fix missing serializable
  src/community/taskmanager/core/src/main/java/org/geoserver/taskmanager/data/LatestBatchRun.java
Labels: backport 2.23.x

#6900 [GEOS-11015] Clean up geopackage tmp files in even wfs output interrupted
  src/extension/geopkg-output/src/main/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormat.java
  src/extension/geopkg-output/src/test/java/org/geoserver/geopkg/wfs/GeoPackageGetFeatureOutputFormatTest.java
Labels: backport 2.22.x, backport 2.23.x

#6916 [GEOS-10949] URL Check UI and documentation improvements
  doc/en/user/source/security/images/regex.png
  doc/en/user/source/security/images/urlchecks-edit.png
  doc/en/user/source/security/images/urlchecks-test.png
  doc/en/user/source/security/images/urlchecks.png
  doc/en/user/source/security/urlchecks.rst
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/RemoteRequestInputProvider.java
  src/main/src/main/java/org/geoserver/security/urlchecks/GeoServerURLChecker.java
  src/web/security/core/src/main/java/org/geoserver/security/web/url/RegexCheckPage.java
  src/web/security/core/src/main/java/org/geoserver/security/web/url/URLChecksPage.html
  src/web/security/core/src/main/java/org/geoserver/security/web/url/URLChecksPage.java
  src/web/security/core/src/main/resources/GeoServerApplication.properties
  src/web/security/core/src/test/java/org/geoserver/security/web/url/RegexCheckPageTest.java
Labels: backport 2.22.x, backport 2.23.x

#6937 [GEOS-10949] URLChecksPage formatting
  src/web/security/core/src/main/java/org/geoserver/security/web/url/URLChecksPage.html
Labels: backport 2.22.x, backport 2.23.x

#6928 [GEOS-11024] metadata: add datetime field type to feature catalog
  src/extension/metadata/src/main/resources/org/geoserver/metadata/data/service/impl/featureCatalog.yaml
  src/extension/metadata/src/test/java/org/geoserver/metadata/data/service/ConfigurationServiceTest.java
Labels: backport 2.22.x, backport 2.23.x

#6907 [GEOS-10932] csw-iso: should only add 'xsi:nil = false' attribute (pa…
  src/extension/csw/csw-iso/src/main/java/org/geoserver/csw/response/MetaDataTransformer.java
  src/extension/csw/csw-iso/src/test/java/org/geoserver/csw/store/internal/iso/GetRecordsTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x, backport 2.23.x

#6936 [GEOS-11025] projection parameter takes no effect on MongoDB Schemaless features WFS requests
  src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoComplexReader.java
  src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoSchemalessFeatureSource.java
  src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/mappers/SchemalessMongoToComplexMapper.java
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WMSSchemalessMongoTest.java
  src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/wms-results/stations-reprojected.png
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x, backport 2.23.x

#6939 [GEOS-11026] Only WARN on h2 unload failure if H2 driver available
  src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java
Labels: backport 2.23.x

#6908 [GEOS-10979] metadata: don't crash on missing properties file
  src/extension/metadata/src/main/java/org/geoserver/metadata/web/resource/WicketResourceResourceLoader.java
  src/extension/metadata/src/test/java/org/geoserver/metadata/AbstractMetadataTest.java
  src/extension/metadata/src/test/java/org/geoserver/metadata/EmptyConfigurationTest.java
Labels: backport 2.22.x, backport 2.23.x

#6938 [GEOS-11036] The OAuth2*/OIDC security filters do not work as expected anymore after the spring-security-core depencency update to 5.7.8
  src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuth2SecurityConfiguration.java
  src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
Labels: backport 2.23.x

#6868 WIP [GEOS-11000] WPS process to provide elevation profile for a linestring
  doc/en/user/source/extensions/index.rst
  doc/en/user/source/extensions/wps-longitudinal-profile/index.rst
  src/community/pom.xml
  src/community/release/ext-wps-longitudinal-profile.xml
  src/community/wps-longitudinal-profile/pom.xml
  src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcess.java
  src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcessPPIO.java
  src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/OperationInfo.java
  src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/ProfileInfo.java
  src/community/wps-longitudinal-profile/src/main/resources/applicationContext.xml
  src/community/wps-longitudinal-profile/src/test/java/org/geoserver/wps/longitudinal/test/LongitudinalProfileProcessTest.java
  src/main/src/test/java/org/geoserver/data/test/AdjustmentLayer.properties
  src/main/src/test/java/org/geoserver/data/test/coverage.zip
  src/web/app/pom.xml
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x, backport 2.23.x

#6978 Fix metadata test failures
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/service/impl/ConfigurationServiceImpl.java
  src/extension/metadata/src/test/java/org/geoserver/metadata/EmptyConfigurationTest.java
Labels: backport 2.23.x
