Repository geoserver/geoserver, pull requests merged in 2023-03, with the labels that each got.

#6645 [Backport 2.22.x] Fix GeoServerDataDirectoryTest clean up after running tests
  src/main/src/test/java/org/geoserver/config/GeoServerDataDirectoryTest.java
Labels: backport 2.21.x

#6649 [GEOS-10878] wps-multidimensional and wps-jdbc are not being deployed on maven repo
  src/extension/pom.xml
Labels: backport 2.21.x, backport 2.22.x

#6605 [GEOS-3978] Layer configuration allows admin to enter a zero area bound…
  src/pom.xml
  src/web/core/src/main/java/org/geoserver/web/wicket/EnvelopePanel.java
  src/web/core/src/main/resources/GeoServerApplication.properties
  src/web/core/src/main/resources/GeoServerApplication_ru.properties
  src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupEditPageTest.java
  src/web/core/src/test/java/org/geoserver/web/wicket/EnvelopePanelBoundingBoxTest.java
Labels: backport 2.21.x, backport 2.22.x

#6611 [GEOS-10863] Update Oracle JDBC driver to 19.18.0.0
  src/pom.xml
Labels: backport 2.21.x, backport 2.22.x

#6669 [GEOS-10890] Wrong path for the license file in the Windows installer script
  src/release/installer/win/build/geoserver_winsetup.nsi
Labels: backport 2.22.x, backport 2.23.x

#6674 [[GEOS-10890] Windows installer include html docs and licenses
  src/release/installer/win/build/geoserver_winsetup.nsi
Labels: backport 2.22.x, backport 2.23.x

#6679 [GEOS-10894] Random control-flow errors on Mac builds
  src/extension/control-flow/src/test/java/org/geoserver/flow/controller/AbstractFlowControllerTest.java
  src/extension/control-flow/src/test/java/org/geoserver/flow/controller/PriorityFlowControllerTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6689 [GEOS-10896] Missing NULL check in the template backwards mapping
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
  src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/NamedPlacesDifferentAttributesGeoJSON.json
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GeoJSONGetSimpleFeaturesResponseWFSTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6693 [GEOS-10899] Features template escapes twice HTML produced outputs
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/writers/XMLTemplateWriter.java
  src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLHtmlFeature.xhtml
  src/community/features-templating/features-templating-core/src/test/resources/org/geoserver/featurestemplating/response/HTMLMappedFeature.xhtml
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/HTMLGetSimpleFeaturesResponseWFSTest.java
  src/community/features-templating/features-templating-ows/src/test/resources/org/geoserver/featurestemplating/response/HtmlFeatures.properties
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6684 [GEOS-10865] Backwards incompatible change in the XML representation …
  src/extension/geofence/geofence-server/src/main/java/org/geoserver/geofence/server/rest/GeofenceJaxbRestConfiguration.java
  src/rest/pom.xml
  src/rest/src/main/java/org/geoserver/rest/RestConfiguration.java
  src/restconfig/src/test/java/org/geoserver/rest/security/UserRoleRestControllerTest.java
Labels: backport 2.22.x, backport 2.23.x

#6709 [Backport 2.23.x] [GEOS-10904] Bump jettison from 1.5.3 to 1.5.4
  src/pom.xml
Labels: dependencies

#6707 [Backport 2.21.x] [GEOS-10904] Bump jettison from 1.5.3 to 1.5.4
  src/pom.xml
Labels: dependencies

#6702 [GEOS-10593] Regression: Creating SQL View via REST API and explicit attribute list is no-longer possible
  src/main/src/main/java/org/geoserver/catalog/impl/FeatureTypeValidator.java
  src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/FeatureTypeControllerTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6711 [GEOS-10905] Default CSW properties do not allow sorting by identifiers
  src/extension/csw/core/src/main/resources/org/geoserver/csw/store/internal/Record.default.properties
  src/extension/csw/csw-iso/src/main/resources/org/geoserver/csw/store/internal/MD_Metadata.default.properties
Labels: backport 2.23.x

#6718 [GEOS-10907] Update spring.version from 5.3.25 to 5.3.26 and spring.security.version from 5.7.6 to 5.7.7
  src/pom.xml
Labels: dependencies, backport 2.23.x

#6720 [GEOS-10908] Update spring version from 5.2.22 to 5.2.23
  src/pom.xml
Labels: dependencies, backport 2.21.x

#6724 [GEOS-10909] Don't link from OGC API Features to WFS 2.0 DescribeFeatureType output, if WFS is disabled
  src/community/ogcapi/ogcapi-features/src/main/java/org/geoserver/ogcapi/v1/features/CollectionDocument.java
  src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/CollectionTest.java
Labels: backport 2.23.x

#6737 [GEOS-10759] Update welcome page screen snaps, and selectionMode text instructions
  doc/en/user/source/gettingstarted/web-admin-quickstart/logged_in.png
  doc/en/user/source/installation/images/success.png
  doc/en/user/source/production/config.rst
  doc/en/user/source/production/images/selector_text.png
  doc/en/user/source/webadmin/images/web-admin.png
  doc/en/user/source/webadmin/images/welcome-admin.png
  doc/en/user/source/webadmin/images/welcome-layer.png
  doc/en/user/source/webadmin/images/welcome-workspace.png
  doc/en/user/source/webadmin/welcome.rst
Labels: backport 2.22.x, backport 2.23.x
