Repository geoserver/geoserver, pull requests merged in 2023-11, with the labels that each got.

#7189 [GEOS-11160] GitHub workflow updates for consistency
  .github/workflows/assembly.yml
  .github/workflows/docs.yml
  .github/workflows/linux.yml
  .github/workflows/linux_jdk11.yml
  .github/workflows/linux_jdk17.yml
  .github/workflows/macos.yml
  .github/workflows/qa.yml
  .github/workflows/windows.yml
Labels: backport 2.24.x

#7241 Fix URLcheck heading, grammar
  src/web/security/core/src/main/resources/GeoServerApplication.properties
Labels: backport 2.23.x, backport 2.24.x

#7245 [GEOS-11185] Update MapML viewer to latest release 0.12.1 - map-extent attributes
  src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Extent.java
  src/extension/mapml/src/main/resources/viewer/widget/DOMTokenList.js
  src/extension/mapml/src/main/resources/viewer/widget/DOMTokenList.js.map
  src/extension/mapml/src/main/resources/viewer/widget/layer.js
  src/extension/mapml/src/main/resources/viewer/widget/layer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-input.js
  src/extension/mapml/src/main/resources/viewer/widget/map-input.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-link.js
  src/extension/mapml/src/main/resources/viewer/widget/map-link.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml.css
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js.map
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js.map
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x

#7250 [GEOS-11187] Configuring a raster with NaN as NODATA results in two NaN in the nodata band description
  src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
  src/main/src/test/java/org/geoserver/catalog/impl/CatalogBuilderTest.java
  src/main/src/test/resources/org/geoserver/catalog/impl/rat.tiff
Labels: backport 2.23.x, backport 2.24.x

#7256 [GEOS-11193] Add an option to throw an exception when the time nearest match does not fall within search limits
  doc/en/user/source/data/webadmin/img/data_layers_dimension_editor_time.png
  doc/en/user/source/data/webadmin/layers.rst
  src/main/src/main/java/org/geoserver/catalog/DimensionInfo.java
  src/main/src/main/java/org/geoserver/catalog/impl/DimensionInfoImpl.java
  src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java
  src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
  src/platform/src/main/java/org/geoserver/platform/ServiceException.java
  src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditor.html
  src/web/core/src/main/java/org/geoserver/web/data/resource/DimensionEditorBase.java
  src/web/core/src/main/java/org/geoserver/web/data/resource/VectorCustomDimensionEntry.java
  src/web/core/src/main/resources/GeoServerApplication.properties
  src/web/core/src/test/java/org/geoserver/web/data/resource/DimensionEditorTest.java
  src/wms/src/main/java/org/geoserver/wms/GetMapRequest.java
  src/wms/src/main/java/org/geoserver/wms/WMS.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsRasterGetMapTest.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/DimensionsVectorGetMapTest.java
Labels: backport 2.24.x

#7251 [GEOS-11188] Let DownloadProcess handle download requests whose pixel size is larger than integer limits
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
Labels: backport 2.23.x, backport 2.24.x

#7214 [GEOS-11170] OGC API Features "/api" link is broken in OpenAPI page
  src/community/ogcapi/ogcapi-features/src/main/resources/org/geoserver/ogcapi/v1/features/openapi.yaml
Labels: backport 2.24.x

#7264 [GEOS-11200] GetFeatureInfo can fail on rendering transformations that generate a different raster
  src/wms/src/main/java/org/geoserver/wms/featureinfo/RasterLayerIdentifier.java
  src/wms/src/test/java/org/geoserver/wms/featureinfo/GetFeatureInfoJSONTest.java
  src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormat.java
  src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyFormatFactory.java
  src/wms/src/test/java/org/geoserver/wms/tiffspy/GeoTIFFSpyReader.java
  src/wms/src/test/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi
  src/wms/src/test/resources/org/geoserver/wms/featureinfo/jiffleCondition.sld
Labels: backport 2.23.x, backport 2.24.x

#7263 [GEOS-11196] NPE in VectorDownload if ROI not defined
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/VectorDownload.java
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x, backport 2.23.x, backport 2.24.x

#7173 [GEOS-11152] Improve handling special characters in the Simple SVG Renderer
  src/wms/src/main/java/org/geoserver/wms/svg/StreamingSVGMap.java
  src/wms/src/test/java/org/geoserver/wms/svg/SVGMapProducerTest.java
Labels: backport 2.23.x, backport 2.24.x

#7175 [GEOS-11154] Improve handling special characters in the MapML HTML Page
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLControllerTest.java
Labels: backport 2.23.x, backport 2.24.x

#7276 [GEOS-11206] Throw nearest match mismatch exceptions only for WMS
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/BaseDownloadImageProcessTest.java
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadAnimationProcessTest.java
  src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java
Labels: backport 2.23.x, backport 2.24.x

#7275 [GEOS-11203] WMS GetFeatureInfo bad WKT exception for label-geometry
  src/wms/src/main/java/org/geoserver/wms/featureinfo/FeatureInfoStylePreprocessor.java
  src/wms/src/test/java/org/geoserver/wms/featureinfo/RenderingBasedFeatureInfoTest.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetFeatureInfoTest.java
  src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.properties
  src/wms/src/test/resources/org/geoserver/wms/featureinfo/geom-function.sld
Labels: backport 2.24.x

#7302 [GEOS-11219] Upgrade mail and activation libs
  src/community/taskmanager/core/bin/pom.xml
  src/community/taskmanager/core/pom.xml
  src/main/pom.xml
  src/ows/pom.xml
  src/pom.xml
  src/wcs1_0/pom.xml
  src/wcs1_1/pom.xml
  src/web/app/pom.xml
Labels: backport 2.23.x, backport 2.24.x
