Repository geoserver/geoserver, pull requests merged in 2023-05, with the labels that each got.

#6811 [GEOS-10940] Update MapML viewer to release 0.11.0
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java
  src/extension/mapml/src/main/resources/viewer/widget/DOMTokenList.js
  src/extension/mapml/src/main/resources/viewer/widget/DOMTokenList.js.map
  src/extension/mapml/src/main/resources/viewer/widget/README.md
  src/extension/mapml/src/main/resources/viewer/widget/layer.js
  src/extension/mapml/src/main/resources/viewer/widget/layer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml.css
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js.map
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js.map
Labels: backport 2.20.x, backport 2.21.x, backport 2.22.x, backport 2.23.x

#6812 [GEOT-7346] Provide a snapshot tag for documentation build
  doc/en/.gitignore
  doc/en/README.md
  doc/en/build.xml
  doc/en/docguide/source/index.rst
  doc/en/docguide/source/install.rst
  doc/en/docguide/source/workflow.rst
  doc/en/requirements.txt
  doc/en/user/source/conf.py
  doc/en/user/source/installation/docker.rst
  doc/en/user/source/installation/linux.rst
  doc/en/user/source/installation/war.rst
  doc/en/user/source/installation/win_binary.rst
  doc/en/user/source/installation/win_installer.rst
Labels: backport 2.22.x, backport 2.23.x

#6820 [Backport 2.23.x] [GEOT-7346] Provide a snapshot tag for documentation build
  doc/en/.gitignore
  doc/en/README.md
  doc/en/build.xml
  doc/en/docguide/source/index.rst
  doc/en/docguide/source/install.rst
  doc/en/docguide/source/workflow.rst
  doc/en/requirements.txt
  doc/en/user/source/conf.py
  doc/en/user/source/installation/docker.rst
  doc/en/user/source/installation/linux.rst
  doc/en/user/source/installation/war.rst
  doc/en/user/source/installation/win_binary.rst
  doc/en/user/source/installation/win_installer.rst
Labels: backport 2.22.x

#6768 [GEOS-10858] support isolated workspaces other catalogfacades
  src/community/jdbcconfig/src/test/java/org/geoserver/jdbcconfig/catalog/CatalogImplWithJDBCFacadeTest.java
  src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
Labels: backport 2.22.x, backport 2.23.x

#6810 [GEOS-10957] Support ResourceAccessManager implementations returning custom subclasess of AccessLimits
  src/main/src/main/java/org/geoserver/security/AccessLimits.java
  src/main/src/main/java/org/geoserver/security/CoverageAccessLimits.java
  src/main/src/main/java/org/geoserver/security/DataAccessLimits.java
  src/main/src/main/java/org/geoserver/security/VectorAccessLimits.java
  src/main/src/main/java/org/geoserver/security/WMSAccessLimits.java
  src/main/src/main/java/org/geoserver/security/WMTSAccessLimits.java
  src/main/src/main/java/org/geoserver/security/decorators/SecuredFeatureTypeInfo.java
  src/main/src/test/java/org/geoserver/security/decorators/SecuredFeatureTypeInfoTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6809 [GEOS-10955] STAC templates are initialised in the wrong location
  src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACTemplates.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/STACTestSupport.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/TemplatePropertyMapperTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/collections.ftl
Labels: backport 2.23.x

#6836 [GEOS-10975] JMS clustering reports error about ReferencedEnvelope type not being whitelisted in XStream
  src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/JMSXStreamFactory.java
  src/community/jms-cluster/jms-geoserver/src/test/java/org/geoserver/cluster/integration/IntegrationTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6842 [GEOS-10969] Empty CQL_FILTER-parameter should be ignored
  src/main/src/main/java/org/geoserver/ows/kvp/CQLFilterKvpParser.java
  src/main/src/test/java/org/geoserver/ows/kvp/CQLFilterKvpParserTest.java
  src/wfs/src/main/java/org/geoserver/wfs/kvp/BaseFeatureKvpRequestReader.java
  src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
  src/wms/src/test/java/org/geoserver/wms/map/GetMapIntegrationTest.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#6850 [GEOS-10985] B/R of Geoserver catalog is broken with Geoserver 2.23.0
  src/community/backup-restore/core/src/main/java/org/geoserver/backuprestore/reader/CatalogFileReader.java
Labels: backport 2.23.x

#6835 [GEOS-10964] Support virtual services for OSEO/STAC
  doc/en/user/source/community/opensearch-eo/database.rst
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/OpenSearchAccessProvider.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/ArrayHasNullFunction.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCCollectionFeatureStore.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/WorkspaceFeatureSource.java
  src/community/oseo/oseo-core/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
  src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/ArrayHasNullFunctionTest.java
  src/community/oseo/oseo-core/src/test/resources/collection_test_data.sql
  src/community/oseo/oseo-core/src/test/resources/postgis.sql
  src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/AbstractOpenSearchController.java
  src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionsControllerTest.java
  src/community/oseo/oseo-rest/src/test/resources/collection.json
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionsTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/ItemsTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
Labels: backport 2.22.x, backport 2.23.x

#6832 [GEOS-10929] isolated workspace may cause broken links between catalo…
  src/main/src/main/java/org/geoserver/catalog/impl/CatalogEventDispatcher.java
  src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
  src/main/src/main/java/org/geoserver/catalog/impl/ResolvingProxy.java
Labels: backport 2.22.x, backport 2.23.x

#6853 [GEOS-10989] [2.22.x] Update spring.version from 5.2.23.RELEASE to 5.2.24.RELEASE
  src/pom.xml
Labels: dependencies, backport 2.21.x

#6852 [GEOS-10988] Update spring.version from 5.3.26 to 5.3.27 and spring-integration.version from 5.5.17 to 5.5.18
  src/pom.xml
Labels: dependencies, backport 2.23.x

#6871 [GEOS-10998] LayerGroupContainmentCache is being rebuilt on each ApplicationEvent
  src/main/src/main/java/org/geoserver/security/impl/LayerGroupContainmentCache.java
Labels: backport 2.22.x, backport 2.23.x
