Repository geoserver/geoserver, pull requests merged in 2023-08, with the labels that each got.

#7047 remove restput.xml file lurking in base directory
  restput.xml
Labels: backport 2.22.x, backport 2.23.x

#7056 [GEOS-11094] Bump org.hsqldb:hsqldb:2.7.1 to 2.7.2
  src/pom.xml
Labels: dependencies, backport 2.23.x

#7029 [GEOS-11073] csw: add url.base property
  src/extension/csw/core/src/main/java/org/geoserver/csw/store/internal/InternalCatalogStore.java
  src/extension/csw/core/src/test/java/org/geoserver/csw/store/internal/GetRecordsTest.java
  src/extension/csw/core/src/test/resources/org/geoserver/csw/store/internal/Record.properties
Labels: backport 2.23.x

#7051 [GEOS-11089] Performance penalty adding namespaces while loading catalog
  src/main/src/main/java/org/geoserver/catalog/impl/CatalogInfoLookup.java
  src/main/src/main/java/org/geoserver/catalog/impl/DefaultCatalogFacade.java
  src/main/src/main/java/org/geoserver/catalog/impl/NamespaceInfoLookup.java
  src/main/src/test/java/org/geoserver/catalog/impl/NamespaceInfoLookupTest.java
Labels: backport 2.23.x

#7053 [GEOS-11090] Use Catalog streaming API in WorkspacePage
  src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceProvider.java
  src/web/core/src/test/java/org/geoserver/web/data/workspace/WorkspaceProviderTest.java
Labels: backport 2.23.x

#7049 [GEOS-11087] Fix IsolatedCatalogFacade unnecessary performance overhead
  src/main/src/main/java/org/geoserver/catalog/impl/IsolatedCatalogFacade.java
Labels: backport 2.23.x

#7027 [GEOS-11074] GeoFence may not load property file at boot
  src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/config/GeoFenceConfigurationManager.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x

#7030 [GEOS-11068] Keycloak: custom admin role not picked up
  src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
  src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
Labels: backport 2.23.x

#6189 [GEOS-10452] Fixed Role Services for LDAP/Active Directory.
  src/security/ldap/src/main/java/org/geoserver/security/ldap/BindingLdapAuthoritiesPopulator.java
  src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPRoleService.java
  src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUserGroupService.java
  src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUtils.java
  src/security/ldap/src/test/java/org/geoserver/security/ldap/LDAPUtilsTest.java
Labels: backport 2.23.x

#7076 [GEOS-11100] Add opacity parameter to the layer definitions in WPS-Download download maps
  doc/en/user/source/extensions/wps-download/mapAnimationDownload.rst
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/Layer.java
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadMapProcessTest.java
  src/extension/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapRemoteSimple11Opacity.xml
  src/extension/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapRemoteSimple11OpacityOutOfRange.xml
  src/extension/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapSimpleWithAlpha.png
Labels: backport 2.22.x, backport 2.23.x

#7090 Update DataAccessEditPage.java
  src/web/core/src/main/java/org/geoserver/web/data/store/DataAccessEditPage.java
Labels: backport 2.22.x, backport 2.23.x
