Repository geoserver/geoserver, pull requests merged in 2024-02, with the labels that each got.

#7377 [Backport 2.24.x]Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0 in /src (#7358)
  src/extension/authkey/pom.xml
  src/pom.xml
Labels: dependencies

#7378 [Backport 2.23.x] Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0 in /src (#7358)
  src/extension/authkey/pom.xml
  src/pom.xml
Labels: dependencies

#7373 [GEOS-11290] With Oauth enabled, anon users get random auth requests
  src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
Labels: backport 2.23.x, backport 2.24.x

#7354 [GEOS-11205] Layer page: style image fails if it is in isolated works…
  src/web/wms/src/main/java/org/geoserver/wms/web/publish/LegendGraphicAjaxUpdater.java
  src/web/wms/src/main/java/org/geoserver/wms/web/publish/WMSLayerConfig.java
  src/web/wms/src/test/java/org/geoserver/wms/web/data/publish/WMSLayerConfigTest.java
Labels: backport 2.23.x, backport 2.24.x

#7353 [GEOS-11263] hideEmptyRules not working in JSON LegendGraphic
  src/wms/src/main/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicBuilder.java
  src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
Labels: backport 2.23.x, backport 2.24.x

#7368 [GEOS-11288] Improve input validation in ClasspathPublisher
  src/ows/src/main/java/org/geoserver/ows/ClasspathPublisher.java
  src/ows/src/test/java/org/geoserver/ows/ClasspathPublisherTest.java
Labels: backport 2.23.x, backport 2.24.x

#7391 [GEOS-11291] GeoFence: Cleanup stale log4j references
  src/release/ext-geofence-server.xml
Labels: backport 2.23.x, backport 2.24.x

#7417 [GEOS-11260] JNDI tutorial uses outdated syntax
  doc/en/user/source/tutorials/tomcat-jndi/tomcat-jndi.rst
Labels: backport 2.23.x, backport 2.24.x

#7425 Streamline sort parameter spelling in "Search" OGC API - Features Part 5 proposal
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APISearchQuery.java
  src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
Labels: backport 2.24.x

#7392 GEOS-11279 allow one field multiple tabs
  doc/en/user/source/extensions/metadata/uiconfiguration.rst
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/AttributeConfiguration.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/AttributeConfigurationImpl.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/data/dto/impl/CommaSeparatedDeserializer.java
  src/extension/metadata/src/main/java/org/geoserver/metadata/web/panel/attribute/AttributeDataProvider.java
  src/extension/metadata/src/test/java/org/geoserver/metadata/web/TabsTest.java
  src/extension/metadata/src/test/resources/org/geoserver/metadata/metadata-ui.yaml
Labels: backport 2.23.x, backport 2.24.x

#7427 [GEOS-11305] Add layer information in the models backing STAC
  doc/en/user/source/community/opensearch-eo/STAC.rst
  src/community/oseo/oseo-core/pom.xml
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/ListComplexFeatureCollection.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/AbstractMappingStore.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/CollectionLayer.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/ComplexFeatureBuilder.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCProductFeatureStore.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OpenSearchAccess.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OrderedTypeBuilder.java
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/OutputFormatProvider.java
  src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessIntegrationTest.java
  src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccessTest.java
  src/community/oseo/oseo-core/src/test/java/org/geoserver/opensearch/eo/store/OutputFormatProviderTest.java
  src/community/oseo/oseo-rest/src/main/java/org/geoserver/opensearch/rest/CollectionsController.java
  src/community/oseo/oseo-rest/src/test/java/org/geoserver/opensearch/rest/CollectionLayerTest.java
  src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/ServiceProviderTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/CollectionLayersTest.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/STACTestSupport.java
  src/community/oseo/oseo-stac/src/test/resources/collection-layers.ftl
  src/community/oseo/oseo-stac/src/test/resources/collection-layers.json
  src/community/oseo/web-oseo/src/test/java/org/geoserver/opensearch/eo/web/OSEOAdminPageTest.java
Labels: backport 2.23.x, backport 2.24.x
