Repository geoserver/geoserver, pull requests merged in 2024-11, with the labels that each got.

#7982 More Windows VM tolerance for FileSystemResourceTheoryTest
  src/platform/src/test/java/org/geoserver/platform/resource/FileSystemResourceTheoryTest.java
Labels: backport 2.25.x, backport 2.26.x

#8010 Remove duplicate dependency declaration for gt-cql2-text in the root pom
  src/pom.xml
Labels: backport 2.26.x

#8015 Clarify the requirements for Content dependent legends parameters
  doc/en/user/source/services/wms/get_legend_graphic/index.rst
Labels: backport 2.25.x, backport 2.26.x

#8003 Update SQL Server supported versions
  doc/en/user/source/data/database/sqlserver.rst
Labels: Documentation

#8036 [GEOS-11610] Update Jetty from 9.4.55.v20240627 to 9.4.56.v20240826
  src/pom.xml
Labels: dependencies, backport 2.25.x, backport 2.26.x

#8048 [GEOS-11615] Update to Imageio-EXT 1.4.14
  src/pom.xml
Labels: backport 2.26.x

#8041 [GEOS-11611] When Extracting the WFS Service Name from the HTTP Request A Slash Before the Question Marks Causes Issues
  src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
  src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetFeatureTest.java
  src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
Labels: backport 2.25.x, backport 2.26.x

#8071 Avoid log flooding by GeoJSONGetFeatureResponse
  src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONGetFeatureResponse.java
Labels: backport 2.26.x
