Repository geoserver/geoserver, pull requests merged in 2024-04, with the labels that each got.

#7530 [GEOS-11236] WFS 2.0.0/GetFeature - Shapefile - We have had issues trying to flip axis
  src/main/src/main/java/org/geoserver/catalog/ResourcePool.java
  src/main/src/test/java/org/geoserver/catalog/ResourcePoolTest.java
  src/main/src/test/resources/org/geoserver/catalog/mini-states.zip
  src/wfs/src/main/java/org/geoserver/wfs/WFSReprojectionUtil.java
  src/wfs/src/test/java/org/geoserver/wfs/WFSReprojectionUtilTest.java
Labels: backport 2.23.x, backport 2.24.x, backport 2.25.x

#7538 [GEOS-11362] Upgrade Spring libs from 5.3.32 to 5.3.33
  src/pom.xml
Labels: dependencies, backport 2.24.x, backport 2.25.x

#7536 [GEOS-11359] Update MapML viewer to release 0.13.2
  src/extension/mapml/src/main/resources/viewer/widget/layer.js
  src/extension/mapml/src/main/resources/viewer/widget/layer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js
  src/extension/mapml/src/main/resources/viewer/widget/map-area.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-input.js
  src/extension/mapml/src/main/resources/viewer/widget/map-input.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-link.js
  src/extension/mapml/src/main/resources/viewer/widget/map-link.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-select.js
  src/extension/mapml/src/main/resources/viewer/widget/map-select.js.map
  src/extension/mapml/src/main/resources/viewer/widget/map-style.js
  src/extension/mapml/src/main/resources/viewer/widget/map-style.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js.map
  src/extension/mapml/src/main/resources/viewer/widget/mapml.css
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js.map
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js
  src/extension/mapml/src/main/resources/viewer/widget/web-map.js.map
Labels: backport 2.24.x, backport 2.25.x

#7537 [GEOS-11360] Upgrade Apache POI from 4.1.1 to 5.2.5
  src/pom.xml
Labels: dependencies, backport 2.24.x, backport 2.25.x

#7525 [GEOS-11347] STAC Landing Page links should include root link
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/Link.java
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/OGCAPIMediaTypes.java
  src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACLandingPage.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/LandingPageTest.java
Labels: backport 2.24.x, backport 2.25.x

#7535 [GEOS-11358] Feature-Autopopulate Update operation does not apply the Update Element filter
  src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplate.java
  src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTemplateLoader.java
  src/community/features-autopopulate/features-autopopulate-core/src/main/java/org/geoserver/autopopulate/AutopopulateTransactionCallback.java
  src/community/features-autopopulate/features-autopopulate-core/src/test/java/org/geoserver/autopopulate/AutopopulateTransactionCallbackTest.java
Labels: backport 2.23.x, backport 2.24.x, backport 2.25.x

#7553 [GEOS-11306] Chace GetFeature total using AtomicLong for thread safety
  src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
Labels: backport 2.24.x, backport 2.25.x

#7551 [GEOS-11331] OAuth2 can throw a " java.lang.RuntimeException: Never should reach this point"
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
  src/main/src/main/java/org/geoserver/security/filter/GeoServerPreAuthenticatedUserNameFilter.java
Labels: backport 2.23.x, backport 2.24.x, backport 2.25.x

#7562 [GEOS-11311] Show a full stack trace in the JVM stack dump panel
  src/web/core/src/main/java/org/geoserver/web/system/status/ConsoleInfoUtils.java
  src/web/core/src/test/java/org/geoserver/web/system/status/ConsoleInfoUtilsStackTest.java
Labels: backport 2.23.x, backport 2.24.x, backport 2.25.x

#7575 [GEOS-11375] GSIP 224 - Individual contributor clarification
  doc/en/developer/source/policies/committing.rst
Labels: backport 2.24.x, backport 2.25.x

#7581 [GEOS-11376] Graduate Raster Attribute Table to extension
  doc/en/user/source/community/index.rst
  doc/en/user/source/extensions/index.rst
  doc/en/user/source/extensions/rat/images/rat_map.png
  doc/en/user/source/extensions/rat/images/rat_panel.png
  doc/en/user/source/extensions/rat/index.rst
  doc/en/user/source/extensions/rat/installing.rst
  doc/en/user/source/extensions/rat/using.rst
  src/community/pom.xml
  src/community/release/pom.xml
  src/extension/pom.xml
  src/extension/rat/pom.xml
  src/extension/rat/src/main/java/org/geoserver/rat/CoverageRATs.java
  src/extension/rat/src/main/java/org/geoserver/rat/RasterAttributeTable.java
  src/extension/rat/src/main/java/org/geoserver/rat/rest/PAMController.java
  src/extension/rat/src/main/java/org/geoserver/rat/web/RasterAttributeTableConfig.html
  src/extension/rat/src/main/java/org/geoserver/rat/web/RasterAttributeTableConfig.java
  src/extension/rat/src/main/java/org/geoserver/rat/web/RowProvider.java
  src/extension/rat/src/main/resources/GeoServerApplication.properties
  src/extension/rat/src/main/resources/applicationContext.xml
  src/extension/rat/src/test/java/org/geoserver/rat/RasterAttributeTableTest.java
  src/extension/rat/src/test/java/org/geoserver/rat/rest/PAMControllerTest.java
  src/extension/rat/src/test/java/org/geoserver/rat/web/RasterAttributeTableConfigTest.java
  src/extension/rat/src/test/resources/org/geoserver/rat/norat.xml
  src/extension/rat/src/test/resources/org/geoserver/rat/rangeColors.xml
  src/extension/rat/src/test/resources/org/geoserver/rat/rangeNoColor.xml
  src/extension/rat/src/test/resources/org/geoserver/rat/valueColors.xml
  src/extension/rat/src/test/resources/org/geoserver/rat/valueNoColors.xml
  src/extension/rat/src/test/resources/org/geoserver/rat/web/rat.tiff
  src/extension/rat/src/test/resources/org/geoserver/rat/web/rat.tiff.aux.xml
  src/pom.xml
  src/release/ext-rat.xml
  src/release/pom.xml
  src/web/app/pom.xml
Labels: backport 2.25.x
