Repository geoserver/geoserver, pull requests merged in 2024-10, with the labels that each got.

#7916 [GEOS-11517] Using various OGC APIs results in service enabled check related WARN logs
  src/community/ogcapi/dggs/ogcapi-dggs/src/main/java/org/geoserver/ogcapi/v1/dggs/DGGSService.java
  src/community/ogcapi/dggs/ogcapi-dggs/src/test/java/org/geoserver/ogcapi/v1/dggs/LandingPageTest.java
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIDispatcher.java
  src/community/ogcapi/ogcapi-coverages/src/main/java/org/geoserver/ogcapi/v1/coverages/CoveragesService.java
  src/community/ogcapi/ogcapi-coverages/src/test/java/org/geoserver/ogcapi/v1/coverages/LandingPageTest.java
  src/community/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/LandingPageTest.java
  src/community/ogcapi/ogcapi-images/src/main/java/org/geoserver/ogcapi/v1/images/ImagesService.java
  src/community/ogcapi/ogcapi-images/src/test/java/org/geoserver/ogcapi/v1/images/LandingPageTest.java
  src/community/ogcapi/ogcapi-maps/src/main/java/org/geoserver/ogcapi/v1/maps/MapsService.java
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/LandingPageTest.java
  src/community/ogcapi/ogcapi-styles/src/main/java/org/geoserver/ogcapi/v1/styles/StylesService.java
  src/community/ogcapi/ogcapi-styles/src/test/java/org/geoserver/ogcapi/v1/styles/LandingPageTest.java
  src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACService.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/LandingPageTest.java
  src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
  src/platform/src/main/java/org/geoserver/platform/OWS20Exception.java
  src/platform/src/main/java/org/geoserver/platform/ServiceException.java
Labels: backport 2.25.x, backport 2.26.x

#7922 [GEOS-11559] The customized attributes editor is prone to setting the wrong attribute source
  src/main/src/main/java/org/geoserver/catalog/AttributeTypeInfo.java
  src/main/src/main/java/org/geoserver/catalog/impl/AttributeTypeInfoImpl.java
  src/web/core/src/main/java/org/geoserver/web/data/resource/AttributeTypeInfoEditor.java
  src/web/core/src/test/java/org/geoserver/web/data/resource/ResourceConfigurationPageTest.java
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x

#7921 [GEOS-11560] OGC API modules lack cql2-json in assembly
  src/community/ogcapi/ogcapi-core/pom.xml
  src/community/oseo/oseo-assembly/src/assembly/assembly.xml
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#7930 [GEOS-11561]: Support client-delegating MapML-Proxy
  doc/en/user/source/extensions/mapml/installation.rst
  src/extension/mapml/pom.xml
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLConstants.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLLayerConfigurationPanel.html
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLLayerConfigurationPanel.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLURLBuilder.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/tcrs/TiledCRSConstants.java
  src/extension/mapml/src/main/resources/GeoServerApplication.properties
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLBaseProxyTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSDataAccessProxyTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSGetFeatureInfoProxyTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSProxyTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMTSProxyTest.java
  src/extension/mapml/src/test/resources/__files/wmscaps.xml
  src/extension/mapml/src/test/resources/__files/wmscapsgmlfeatureinfo.xml
  src/extension/mapml/src/test/resources/__files/wmtscaps.xml
Labels: backport 2.26.x

#7947 [GEOS-11565] Allow configuring the minimum and maximum resolution for a layer
  src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java
  src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java
  src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html
  src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.java
  src/community/ogcapi/dggs/web-dggs/src/main/resources/GeoServerApplication.properties
  src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/web/publish/dggs/DGGSConfigPanelTest.java
  src/main/src/main/java/org/vfny/geoserver/global/GeoServerFeatureSource.java
Labels: backport 2.25.x, backport 2.26.x

#7942 Add missing JARs to assembly.xml file for cog-s3 plugin
  src/community/cog/cog-s3/src/assembly/assembly.xml
Labels: backport 2.26.x

#7989 [GEOS-11587] Update mapfish-print-v2 to version 2.3.2
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#7992 [GEOS-11588] Use JDBCConfiguration.validateConfiguration to provide feedback
  doc/en/user/source/installation/upgrade.rst
  src/gwc/pom.xml
  src/gwc/src/main/java/org/geoserver/gwc/JDBCConfigurationStorage.java
  src/gwc/src/test/java/org/geoserver/gwc/GWCIntegrationTest.java
Labels: backport 2.25.x, backport 2.26.x

#7997 Bump GeoFence to 3.7.2
  src/pom.xml
Labels: dependencies, backport 2.25.x, backport 2.26.x

#7996 [GEOS-11141] Change docs to workspace admin recommendation
  doc/en/user/source/production/config.rst
  doc/en/user/source/webadmin/index.rst
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x
