Repository geoserver/geoserver, pull requests merged in 2024-05, with the labels that each got.

#7586 [GEOS-11381] Fix error in OIDC plugin in combination with RoleService
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
Labels: backport 2.23.x, backport 2.24.x, backport 2.25.x

#7583 [GEOS-11377] RAT module: allow to reload/recompute the RAT
  doc/en/api/1.0.0/rat.yaml
  src/extension/rat/src/main/java/org/geoserver/rat/rest/PAMController.java
  src/extension/rat/src/test/java/org/geoserver/rat/rest/PAMControllerTest.java
  src/extension/rat/src/test/resources/org/geoserver/rat/web/rat.tiff.aux2.xml
Labels: backport 2.25.x

#7604 [GEOS-11388] Update ImageIO-EXT to 1.4.10
  src/pom.xml
Labels: backport 2.25.x

#7603 [GEOS-11386] GSIP-223 Community module graduation, amending generality rule
  doc/en/developer/source/policies/community-modules.rst
Labels: backport 2.24.x, backport 2.25.x

#7590 [GEOS-11382] The interceptor "CiteComplianceHack" never gets invoked by the Dispatcher Servlet
  src/extension/csw/core/src/test/java/org/geoserver/csw/GetCapabilitiesTest.java
  src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
  src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
  src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
  src/wfs/src/test/java/org/geoserver/wfs/GetFeatureTest.java
  src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
  src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetCapabilitiesTest.java
  src/wms/src/main/java/applicationContext.xml
  src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
Labels: backport 2.24.x, backport 2.25.x

#7616 [GEOS-11392] ConcurrentModificationException while using proxy-base-ext
  src/community/proxy-base-ext/src/main/java/org/geoserver/proxybase/ext/ProxyBaseExtUrlMangler.java
Labels: backport 2.25.x

#7618 [GEOS-11393] Upgrade commons-io from 2.12.0 to 2.16.1
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/MaxSizeInputStream.java
  src/pom.xml
Labels: backport 2.24.x, backport 2.25.x

#7619 [GEOS-11395] Upgrade guava from 32.0.0 to 33.2.0
  src/pom.xml
Labels: backport 2.24.x, backport 2.25.x

#7602 [GEOS-11385] Demo Requests functionality does not honour ENV variable PROXY_BASE_URL
  src/wfs/src/main/java/org/vfny/geoserver/wfs/servlets/TestWfsPost.java
  src/wfs/src/test/java/org/geoserver/wfs/v1_1/GetCapabilitiesTest.java
  src/wfs/src/test/java/org/vfny/geoserver/wfs/servlets/TestWfsPostTest.java
Labels: backport 2.24.x, backport 2.25.x

#7632 Avoid wanings about IAU missing in GWC test logs
  src/gwc/pom.xml
Labels: backport 2.25.x

#7571 [GEOS-11202] Respect proxy base URL when building CAS service URL.
  src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java
  src/extension/security/cas/src/test/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilterTest.java
Labels: backport 2.24.x, backport 2.25.x

#7580 [GEOS-11332] Renaming style with uppercase/downcase empty the sld file
  src/platform/src/main/java/org/geoserver/util/IOUtils.java
  src/platform/src/test/java/org/geoserver/util/IOUtilsTest.java
Labels: backport 2.24.x, backport 2.25.x

#7643 [GEOS-11402] Upgrade PostgreSQL driver from 42.7.2 to 42.7.3
  src/pom.xml
Labels: backport 2.24.x, backport 2.25.x

#7644 [GEOS-11403] Upgrade commons-text from 1.10.0 to 1.12.0
  src/pom.xml
Labels: backport 2.24.x, backport 2.25.x

#7645 [GEOS-11404] Upgrade commons-codec from 1.15 to 1.17.0
  src/pom.xml
Labels: backport 2.24.x, backport 2.25.x

#7621 [GEOS-11394] OGC APIs cannot handle time extent when the source data type is java.sql.Date
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/CollectionExtents.java
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/TimeExtentCalculator.java
  src/community/ogcapi/ogcapi-core/src/main/resources/org/geoserver/ogcapi/common-header.ftl
  src/community/ogcapi/ogcapi-coverages/src/main/resources/org/geoserver/ogcapi/v1/coverages/collection_include.ftl
  src/community/ogcapi/ogcapi-maps/src/main/resources/org/geoserver/ogcapi/v1/maps/collection_include.ftl
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/CollectionTest.java
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTest.java
  src/community/ogcapi/ogcapi-maps/src/test/java/org/geoserver/ogcapi/v1/maps/MapsTestSupport.java
  src/community/ogcapi/ogcapi-maps/src/test/resources/org/geoserver/ogcapi/v1/maps/TimeElevationWithStartEndDate.properties
  src/main/src/main/java/org/geoserver/template/FeatureWrapper.java
Labels: backport 2.25.x

#7669 [GEOS-11408] XmlRequestReader clean generic XML request parsing exceptions
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/xml/v1_0_0/WpsXmlReader.java
  src/ows/src/main/java/org/geoserver/ows/XmlRequestReader.java
  src/ows/src/test/java/org/geoserver/ows/DispatcherTest.java
  src/ows/src/test/java/org/geoserver/ows/MessageXmlParser.java
  src/wcs1_0/src/main/java/org/geoserver/wcs/xml/v1_0_0/WcsXmlReader.java
  src/wcs1_1/src/main/java/org/geoserver/wcs/xml/v1_1_1/WcsXmlReader.java
  src/wcs2_0/src/main/java/org/geoserver/wcs2_0/xml/WcsXmlReader.java
  src/wfs/src/main/java/org/geoserver/wfs/xml/v1_0_0/WfsXmlReader.java
  src/wfs/src/main/java/org/geoserver/wfs/xml/v1_1_0/WfsXmlReader.java
  src/wfs/src/main/java/org/geoserver/wfs/xml/v2_0/WfsXmlReader.java
  src/wfs/src/test/java/org/geoserver/wfs/ExternalEntitiesTest.java
  src/wms/src/main/java/org/geoserver/sld/SLDXmlRequestReader.java
  src/wms/src/main/java/org/geoserver/wms/capabilities/CapabilitiesXmlReader.java
  src/wms/src/main/java/org/geoserver/wms/map/GetMapXmlReader.java
  src/wms/src/test/java/org/geoserver/wms/map/GetMapXmlReaderTest.java
  src/wms/src/test/resources/org/geoserver/wms/map/WMSPostServiceException.xml
Labels: backport 2.24.x, backport 2.25.x

#7668 [GEOS-11398] Javadoc clarification and test cases for Entity Resolution
  src/main/src/main/java/org/geoserver/config/GeoServerInfo.java
  src/main/src/main/java/org/geoserver/config/impl/GeoServerInfoImpl.java
  src/main/src/main/java/org/geoserver/util/AllowListEntityResolver.java
  src/main/src/main/java/org/geoserver/util/EntityResolverProvider.java
  src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
  src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
Labels: backport 2.24.x, backport 2.25.x

#7680 [GEOS-11398] Additional entityResolverProviderTest checks
  src/main/src/test/java/org/geoserver/util/EntityResolverProviderTest.java
Labels: backport 2.25.x

#7682 war bundle has license and licenses folder
  src/release/war.xml
Labels: backport 2.24.x, backport 2.25.x

#7683 [GEOS-11411] Upgrade to ImageIO-EXT 1.4.11
  src/pom.xml
Labels: backport 2.24.x, backport 2.25.x

#7693 [GEOS-11412] JMS failure because of missing JDOM jar
  src/community/jms-cluster/jms-geoserver/pom.xml
  src/community/jms-cluster/jms-geoserver/src/main/java/org/geoserver/cluster/impl/handlers/DocumentFile.java
Labels: backport 2.21.x, backport 2.22.x, backport 2.23.x, backport 2.24.x, backport 2.25.x
