Repository geoserver/geoserver, pull requests merged in 2024-12, with the labels that each got.

#8068 Update imagepyramid.rst - remove dead links from docs
  doc/en/user/source/tutorials/imagepyramid/imagepyramid.rst
Labels: backport 2.25.x, backport 2.26.x

#8082 [GEOS-11616] GSIP 229 - File system access isolation. Bug fixes
  src/main/src/main/java/org/geoserver/security/impl/DataAccessRuleDAO.java
  src/security/security-tests/src/test/java/org/geoserver/security/impl/DataAccessRuleDAOTest.java
  src/web/security/core/src/main/java/org/geoserver/security/web/data/DataSecurityPage.java
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x

#8088 [GEOS-11631] Update MySQL driver to 9.1.0
  src/pom.xml
  src/release/ext-mysql.xml
  src/release/extensions/mysql/mysql-README.md
  src/security/jdbc/pom.xml
Labels: dependencies, backport 2.25.x, backport 2.26.x

#8087 [GEOS-11630] REST API throws HTTP 500 When Security Metadata Has Null Attributes
  src/main/src/main/java/org/geoserver/security/RESTfulDefinitionSource.java
  src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityInterceptorFilter.java
  src/main/src/test/java/org/geoserver/security/filter/GeoServerRequestHeaderAuthenticationFilterTest.java
Labels: backport 2.26.x

#8042 [GEOS-11612] Add proxy base url use headers system property support
  doc/en/user/source/configuration/globalsettings.rst
  doc/en/user/source/configuration/properties/index.rst
  src/main/src/main/java/org/geoserver/ows/ProxifyingURLMangler.java
  src/main/src/main/java/org/vfny/geoserver/util/Requests.java
  src/main/src/test/java/org/geoserver/ows/URLManglersTest.java
Labels: backport 2.25.x, backport 2.26.x

#8103 [Backport 2.25.x] [GEOS-11631] Update MySQL driver to 9.1.0
  src/pom.xml
  src/release/ext-mysql.xml
  src/release/extensions/mysql/mysql-README.md
  src/security/jdbc/pom.xml
Labels: dependencies

#8101 Upgrade wiremock from 2.35.1 to 3.10.0
  .github/workflows/assembly.yml
  src/community/security/keycloak/pom.xml
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
  src/community/web-service-auth/pom.xml
  src/community/web-service-auth/src/test/java/org/geoserver/security/auth/WebAuthProviderTest.java
  src/extension/mapml/pom.xml
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLBaseProxyTest.java
  src/extension/wps/wps-core/pom.xml
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ExecuteURLCheckTest.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/executor/RemoteRequestInputProviderTest.java
  src/pom.xml
  src/web/core/pom.xml
  src/web/core/src/test/java/org/geoserver/web/data/store/WMSStoreNewPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/WMTSStoreNewPageTest.java
  src/wms/pom.xml
  src/wms/src/test/java/org/geoserver/wms/wms_1_1_1/GetMapURLCheckersTest.java
Labels: backport 2.26.x

#8105 Github actions: updating artifact upload/download to v4
  .github/workflows/cite.yml
Labels: backport 2.25.x, backport 2.26.x

#8108 [GEOS-11636] Store panels won't always show feedback in target panels
  src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
  src/web/core/src/test/java/org/geoserver/web/data/store/CoverageStoreNewPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessEditPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessNewPageTest.java
Labels: backport 2.25.x, backport 2.26.x

#8109 [2.26.x backport] [GEOS-11636] Store panels won't always show feedback in target panels
  src/web/core/src/main/java/org/geoserver/web/GeoServerApplication.java
  src/web/core/src/main/java/org/geoserver/web/data/store/AbstractCoverageStorePage.java
  src/web/core/src/main/java/org/geoserver/web/data/store/AbstractDataAccessPage.java
  src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMSStorePage.java
  src/web/core/src/main/java/org/geoserver/web/data/store/AbstractWMTSStorePage.java
  src/web/core/src/test/java/org/geoserver/web/data/store/CoverageStoreNewPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessEditPageTest.java
  src/web/core/src/test/java/org/geoserver/web/data/store/DataAccessNewPageTest.java
Labels: backport 2.25.x

#8111 [GEOS-11637] DGGS min/max resolution settings stop working after restart
  src/community/ogcapi/dggs/dggs-core/src/main/java/org/geotools/dggs/gstore/DGGSResolutionCalculator.java
  src/community/ogcapi/dggs/dggs-core/src/test/java/org/geotools/dggs/gstore/DGGSResolutionCalculatorTest.java
  src/community/ogcapi/dggs/web-dggs/src/main/java/org/geoserver/web/publish/dggs/DGGSConfigPanel.html
  src/community/ogcapi/dggs/web-dggs/src/test/java/org/geoserver/dggs/DGGSIntegrationTest.java
Labels: backport 2.25.x, backport 2.26.x

#7971 [GEOS-11494] WFS GetFeature request with a propertyname parameter fails when layer attributes are customized
  src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
Labels: backport 2.25.x, backport 2.26.x

#8116 [GEOS-11643] WCS input read limits can be fooled by geotiff reader
  src/wcs/src/main/java/org/vfny/geoserver/util/WCSUtils.java
  src/wcs/src/test/java/org/vfny/geoserver/util/WCSUtilsTest.java
  src/wcs1_0/src/main/java/org/geoserver/wcs/DefaultWebCoverageService100.java
  src/wcs1_0/src/test/java/org/geoserver/wcs/GetCoverageTest.java
  src/wcs1_1/src/main/java/org/geoserver/wcs/DefaultWebCoverageService111.java
  src/wcs1_1/src/test/java/org/geoserver/wcs/GetCoverageTest.java
  src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GetCoverage.java
  src/wcs2_0/src/test/java/org/geoserver/wcs2_0/xml/GetCoverageTest.java
  src/wcs2_0/src/test/resources/requestGetCoverageSlice.xml
Labels: backport 2.25.x, backport 2.26.x

#8117 [GEOS-11644] Introducing the rest/security/acl/catalog/reload rest endpoint
  doc/en/api/1.0.0/security.yaml
  src/restconfig/src/main/java/org/geoserver/rest/security/CatalogSecurityController.java
  src/restconfig/src/test/java/org/geoserver/rest/security/AccessControllersTest.java
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x

#8022 [GEOS-11608] Update Bouncy Castle Crypto package from bcprov-jdk15on:1.69 to bcprov-jdk18on:1.79
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
  src/main/pom.xml
  src/pom.xml
  src/web/core/pom.xml
  src/web/security/ldap/pom.xml
  src/wms/pom.xml
Labels: dependencies, backport 2.26.x

#8132 [GEOS-11651] Support env parametrization on OIDC filter
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdFilterConfigTest.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/resources/geoserver-environment.properties
  src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuth2FilterConfig.java
  src/community/security/oauth2/oauth2-core/src/test/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilterTest.java
  src/community/security/oauth2/oauth2-core/src/test/resources/geoserver-environment.properties
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x

#8136 [GEOS-11652] Externalize printing configuration folder
  doc/en/user/source/extensions/printing/index.rst
  src/extension/printing/pom.xml
  src/extension/printing/src/main/java/org/geoserver/printing/PrintingServletWrappingController.java
  src/extension/printing/src/test/java/org/geoserver/printing/PrintingServletWrappingControllerTest.java
  src/extension/printing/src/test/java/org/geoserver/printing/SmokeTest.java
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x

#8141 [GEOS-11654] Fix multiline strings that are missing a space between the lines
  src/community/features-templating/features-templating-core/src/main/java/org/geoserver/featurestemplating/request/TemplatePathVisitor.java
  src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIBBoxParser.java
  src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/ApiTest.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
  src/gwc/src/main/java/org/geoserver/gwc/layer/GeoServerTileLayer.java
  src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
  src/main/src/main/java/org/geoserver/logging/LoggingUtilsDelegate.java
  src/wcs1_0/src/main/java/org/geoserver/wcs/kvp/BBoxKvpParser.java
  src/wcs1_1/src/main/java/org/geoserver/wcs/kvp/BoundingBoxKvpParser.java
  src/wfs/src/main/java/org/geoserver/wfs/WFSGetFeatureOutputFormat.java
  src/wfs/src/main/java/org/geoserver/wfs/kvp/BBoxKvpParser.java
  src/wfs/src/test/java/org/geoserver/wfs/MaxFeaturesTest.java
Labels: backport 2.25.x, backport 2.26.x

#8145 Monitor tests: Github action slowness tolerance
  src/extension/monitor/core/src/test/java/org/geoserver/monitor/PipeliningTaskQueueTest.java
Labels: backport 2.25.x, backport 2.26.x

#8144 Add documentation for the DataDirectory Catalog Loader community module
  doc/en/user/source/community/datadir-catalog-loader/index.rst
  doc/en/user/source/community/index.rst
Labels: backport 2.25.x, backport 2.26.x

#8120 [GEOS-11647] Restore "quiet on not found" configuration for REST in global settings
  src/rest/pom.xml
  src/rest/src/main/java/org/geoserver/rest/RestControllerAdvice.java
  src/rest/src/main/java/org/geoserver/rest/util/RESTUtils.java
  src/rest/src/test/java/org/geoserver/rest/ExceptionHandlingTest.java
  src/rest/src/test/java/org/geoserver/rest/LoggingCapturer.java
Labels: backport 2.26.x

#7809 Remove dependency on xml-apis-xerces on the printing extension
  src/extension/printing/pom.xml
  src/release/ext-printing.xml
Labels: dependencies, backport 2.25.x, backport 2.26.x

#8158 [GEOS-11659] Developer Guide formatting with Palantir
  doc/en/developer/source/eclipse-guide/code_formatting2.png
  doc/en/developer/source/eclipse-guide/index.rst
  doc/en/developer/source/qa-guide/index.rst
  doc/en/developer/source/quickstart/intellij.rst
Labels: backport 2.25.x, backport 2.26.x

#8165 Translations update from OSGeo Weblate
  src/extension/mapml/src/main/resources/GeoServerApplication_fr.properties
  src/web/security/core/src/main/resources/GeoServerApplication_fr.properties
Labels: backport 2.26.x
