Repository geoserver/geoserver, pull requests merged in 2024-01, with the labels that each got.

#7333 [GEOS-11245] Update OSHI from 6.2.2 to 6.4.10
  src/pom.xml
Labels: backport 2.24.x

#7338 [GEOS-11246] Schemaless plugin performance for WFS
  src/community/schemaless-features/schemaless-core/src/main/java/org/geoserver/schemalessfeatures/type/DynamicComplexTypeImpl.java
Labels: backport 2.22.x, backport 2.23.x, backport 2.24.x

#7329 [GEOS-11241] ModificationProxy breaks information hidding on CatalogInfo.accept(CatalogVisitor)
  src/main/src/main/java/org/geoserver/catalog/impl/ModificationProxy.java
  src/main/src/test/java/org/geoserver/catalog/impl/ModificationProxyTest.java
Labels: backport 2.24.x

#7343 [GEOS-11250] WFS GeoJSON encoder fails with an exception if an infinity number is used in the geometry
  doc/en/user/source/services/wfs/outputformats.rst
  src/wfs/src/main/java/org/geoserver/wfs/json/GeoJSONBuilder.java
  src/wfs/src/test/java/org/geoserver/wfs/json/GeoJSONBuilderTest.java
Labels: backport 2.23.x, backport 2.24.x

#7316 [GEOS-11225] AuthKey synchronize the user/group automatically
  doc/en/user/source/extensions/authkey/images/001_auto_sync.png
  doc/en/user/source/extensions/authkey/index.rst
  src/extension/authkey/pom.xml
  src/extension/authkey/src/main/java/org/geoserver/security/AbstractAuthenticationKeyMapper.java
  src/extension/authkey/src/main/java/org/geoserver/security/AuthenticationKeyFilterConfig.java
  src/extension/authkey/src/main/java/org/geoserver/security/AuthenticationKeyMapper.java
  src/extension/authkey/src/main/java/org/geoserver/security/GeoServerAuthenticationKeyProvider.java
  src/extension/authkey/src/main/java/org/geoserver/security/WebServiceAuthenticationKeyMapper.java
  src/extension/authkey/src/main/java/org/geoserver/security/web/AuthenticationKeyFilterPanel.html
  src/extension/authkey/src/main/java/org/geoserver/security/web/AuthenticationKeyFilterPanel.java
  src/extension/authkey/src/main/resources/GeoServerApplication.properties
  src/extension/authkey/src/main/resources/applicationContext.xml
  src/extension/authkey/src/test/java/org/geoserver/security/AuthKeyAuthenticationTest.java
Labels: backport 2.23.x, backport 2.24.x
