Repository geoserver/geoserver, pull requests merged in 2024-06, with the labels that each got.

#7705 Fix typo in datadir-catalog-loader release descriptor (s/dataird/datadir/g)
  src/community/release/ext-datadir-catalog-loader.xml
Labels: backport 2.25.x

#7699 [GEOS-11280] Short-circuit request processing upon ClientStreamAbortedException when SKIP_MISCONFIGURED_LAYERS is true
  src/ows/src/main/java/org/geoserver/ows/ClientStreamAbortedException.java
  src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10CapsTransformer.java
  src/wcs1_0/src/main/java/org/geoserver/wcs/response/Wcs10DescribeCoverageTransformer.java
  src/wcs1_1/src/main/java/org/geoserver/wcs/response/WCSCapsTransformer.java
  src/wfs/src/main/java/org/geoserver/wfs/CapabilitiesTransformer.java
  src/wfs/src/main/java/org/geoserver/wfs/DescribeFeatureType.java
  src/wms/src/main/java/org/geoserver/wms/capabilities/Capabilities_1_3_0_Transformer.java
  src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java
Labels: backport 2.25.x

#7711 [GEOS-11430] CiteComplianceHack not correctly parsing the context
  src/main/src/main/java/org/geoserver/ows/CiteComplianceHack.java
  src/ows/src/main/java/org/geoserver/ows/Dispatcher.java
  src/wms/src/test/java/org/geoserver/wms/wms_1_3/CapabilitiesSystemTest.java
Labels: backport 2.24.x, backport 2.25.x

#7717 Update tutorials/activedirectory/index.rst
  doc/en/user/source/security/tutorials/activedirectory/index.rst
Labels: backport 2.25.x

#7719 [GEOS-11432] Upgrade to ImageIO-EXT 1.4.12
  src/pom.xml
Labels: backport 2.25.x

#7721 [GEOS-11390] Replace TestWfsPost with Javascript Demo Page
  src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSRequestBuilder.java
  src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestsPage.java
  src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilder.java
Labels: backport 2.25.x

#7704 [GEOS-11424] Speed up web-ui WorkspaceAdminComponentAuthorizer
  src/main/src/main/java/org/geoserver/security/ResourceAccessManager.java
  src/web/core/src/main/java/org/geoserver/web/WorkspaceAdminComponentAuthorizer.java
  src/web/core/src/test/java/org/geoserver/web/WorkspaceAdminComponentAuthorizerTest.java
Labels: backport 2.25.x

#7698 [GEOS-11423] Use securityFilter in SecureCatalogImpl bulk get methods
  src/main/src/main/java/org/geoserver/security/SecureCatalogImpl.java
  src/security/security-tests/src/test/java/org/geoserver/ows/LocalWorkspaceSecureCatalogTest.java
Labels: backport 2.25.x

#7730 [GEOS-11111] Open search for EO community module: STAC search page has wrong self link
  src/community/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/PaginationLinksBuilder.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
Labels: backport 2.23.x, backport 2.24.x, backport 2.25.x

#7735 [GEOS-11438] OpenSearch for EO/STAC lack the service configuration panel
  src/community/oseo/oseo-assembly/pom.xml
Labels: backport 2.25.x

#7729 [ci] update workflow actions and maven version
  .github/workflows/assembly.yml
  .github/workflows/backport.yml
  .github/workflows/docs.yml
  .github/workflows/javadoc.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/postgis_appschema_online.yml
  .github/workflows/qa.yml
  .github/workflows/windows.yml
Labels: backport 2.24.x, backport 2.25.x

#7738 [GEOS-11439] JDBCOpenSearch access should cache the list of type name s in request scope
  src/community/oseo/oseo-core/src/main/java/org/geoserver/opensearch/eo/store/JDBCOpenSearchAccess.java
Labels: backport 2.25.x

#7740 [GEOS-11442] Cache availability of gdal_translate in gdal_translate based WCS output formats
  src/community/gdal/gdal-wcs/src/main/java/org/geoserver/wcs/response/GdalCoverageResponseDelegate.java
Labels: backport 2.25.x

#7739 [GEOS-111441] DisabledServiceResourceFilter spams debugging logs with property accesses
  src/main/src/main/java/org/geoserver/security/DisabledServiceResourceFilter.java
  src/wfs/src/test/java/org/geoserver/wfs/WFSDisabledTest.java
Labels: backport 2.25.x

#7741 Added some gs-web-gwc Chinese translations
  src/web/gwc/src/main/resources/GeoServerApplication_zh.properties
Labels: backport 2.25.x

#7724 [GEOS-11336] upgrade keycloak
  src/community/security/keycloak/pom.xml
  src/community/security/keycloak/src/main/java/org/geoserver/security/keycloak/GeoServerKeycloakFilter.java
  src/community/security/keycloak/src/test/java/org/geoserver/security/keycloak/GeoServerKeycloakFilterTest.java
Labels: backport 2.24.x, backport 2.25.x

#7725 Update test images for GEOT-7596
  src/extension/wps-download/src/test/resources/org/geoserver/wps/gs/download/animateBlueMarbleTimestampedFrame1.png
  src/wms/src/test/resources/org/geoserver/wms/map/indexed-bg-expected.png
  src/wms/src/test/resources/org/geoserver/wms/map/indexed-expected.png
Labels: backport 2.25.x
