Repository geoserver/geoserver, pull requests merged in 2024-08, with the labels that each got.

#7776 [GEOS-11470] Upgrade the version of Mongo driver for schemaless plugin from 4.0.6 to 4.11.2
  src/community/schemaless-features/mongodb-schemaless/pom.xml
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WFSSchemalessMongoTest.java
  src/community/schemaless-features/mongodb-schemaless/src/test/java/org/geoserver/schemalessfeatures/mongodb/WMSSchemalessMongoTest.java
  src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/json/stations1.json
  src/community/schemaless-features/mongodb-schemaless/src/test/resources/org/geoserver/schemalessfeatures/mongodb/test-data/stations/query/postQuery.xml
Labels: backport 2.25.x

#7815 [GEOS-7630] Azure blob store may not get environment parameters from property file
  src/community/gwc-azure-blob/src/main/resources/applicationContext.xml
  src/gwc/src/main/resources/geowebcache-core-context.xml
Labels: backport 2.24.x, backport 2.25.x

#7811 Fix cog maven profile for gs-web-app
  src/web/app/pom.xml
Labels: dependencies, backport 2.25.x

#7837 [GEOS-11502] Permit resize on user/group/role palette textbox to allow for extra long role names
  src/web/core/src/main/java/org/geoserver/web/css/geoserver.css
  src/web/security/core/src/main/java/org/geoserver/security/web/PaletteFormComponent.java
  src/web/security/core/src/main/java/org/geoserver/security/web/role/RolePaletteFormComponent.java
  src/web/security/core/src/main/java/org/geoserver/security/web/role/RuleRolesFormComponent.java
  src/web/security/core/src/main/java/org/geoserver/security/web/user/UserGroupPaletteFormComponent.java
Labels: backport 2.25.x

#7638 [GEOS-11399] Use Catalog streaming API in LayerGroupPage
  src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupProvider.java
  src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupProviderFilter.java
  src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupPageTest.java
Labels: backport 2.25.x

#7856 [GEOS-11512] Upgrade jasypt from 1.9.2 to 1.9.3
  src/pom.xml
Labels: backport 2.25.x

#7858 Follow up to GEOT-7636 changes
  src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
Labels: backport 2.25.x

#7860 Added missing reference in ImageMosaic Example
  doc/en/user/source/community/cog/mosaic.rst
Labels: backport 2.24.x, backport 2.25.x

#7857 [GEOS-11514] Fix parsing WPS geometry geojson inputs
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/GeoJSONPPIO.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/ppio/GeoJSONPPIOTest.java
Labels: backport 2.25.x

#7844 [GEOS-11505] Monitor Callback to handle WFS 2.0 `GetFeature` requests
  src/extension/monitor/core/src/main/java/org/geoserver/monitor/ows/MonitorCallback.java
  src/extension/monitor/core/src/main/java/org/geoserver/monitor/ows/wfs20/GetFeature20Handler.java
  src/extension/monitor/core/src/test/java/org/geoserver/monitor/ows/MonitorCallbackTest.java
Labels: backport 2.24.x, backport 2.25.x

#7843 [GEOS-11504] ResourceAccessManagerWrapper misses some delegating methods
  src/main/src/main/java/org/geoserver/security/ResourceAccessManagerWrapper.java
  src/main/src/test/java/org/geoserver/security/ResourceAccessManagerWrapperTest.java
Labels: backport 2.25.x

#7841 [GEOS-11503] Update mongo schemaless DWITHIN to support non-point geometry
  src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/data/MongoSchemalessFeatureSource.java
  src/community/schemaless-features/mongodb-schemaless/src/main/java/org/geoserver/schemalessfeatures/mongodb/filter/SchemalessFilterToMongo.java
Labels: backport 2.24.x, backport 2.25.x
