Repository geoserver/geoserver, pull requests merged in 2024-07, with the labels that each got.

#7752 [GEOS-11446] [INSPIRE] Incorrect behavior for unsupported languages
  src/extension/inspire/src/main/java/org/geoserver/inspire/LanguagesDispatcherCallback.java
  src/extension/inspire/src/main/java/org/geoserver/inspire/ServicesUtils.java
  src/extension/inspire/src/test/java/org/geoserver/inspire/wcs/WCSExtendedCapabilitiesTest.java
  src/extension/inspire/src/test/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesTest.java
  src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java
  src/extension/inspire/src/test/java/org/geoserver/inspire/wmts/WMTSExtendedCapabilitiesTest.java
  src/main/src/main/java/org/geoserver/data/InternationalContentHelper.java
  src/main/src/main/java/org/geoserver/security/impl/DigestAuthUtils.java
  src/ows/src/main/java/org/geoserver/ows/util/RequestUtils.java
Labels: backport 2.24.x, backport 2.25.x

#7763 Update oidc.rst
  doc/en/user/source/community/oauth2/oidc.rst
Labels: backport 2.25.x

#7767 [GEOS-11464] Update Jackson 2 libs from 2.17.1 to 2.17.2
  src/pom.xml
Labels: dependencies, backport 2.24.x, backport 2.25.x

#7774 [GEOS-11469] Datadir catalog loader does not decrypt HTTPStoreInfo passwords
  src/community/datadir-catalog-loader/src/main/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoader.java
  src/community/datadir-catalog-loader/src/test/java/org/geoserver/catalog/datadir/DataDirectoryGeoServerLoaderTest.java
Labels: backport 2.25.x

#7783 [GEOS-11462] 500 error thrown when double adding a user to a group via REST with JDBC user/group services
  src/restconfig/src/main/java/org/geoserver/rest/security/UsersRestController.java
  src/restconfig/src/test/java/org/geoserver/rest/security/UserRoleRestControllerTest.java
Labels: backport 2.24.x, backport 2.25.x

#7768 [GEOS-11443] REST API does not take effect immediately due to 10 minute authentication cache
  doc/en/api/1.0.0/reload.yaml
  doc/en/user/source/rest/api/reset.rst
  src/main/src/main/java/applicationContext.xml
  src/main/src/main/java/applicationSecurityContext.xml
  src/main/src/main/java/org/geoserver/security/GeoServerSecurityManager.java
  src/main/src/main/java/org/geoserver/security/auth/AuthenticationCache.java
  src/main/src/main/java/org/geoserver/security/auth/AuthenticationCacheImpl.java
  src/main/src/main/java/org/geoserver/security/auth/GeoServerRootAuthenticationProvider.java
  src/main/src/main/java/org/geoserver/security/auth/GuavaAuthenticationCacheImpl.java
  src/main/src/main/java/org/geoserver/security/auth/LRUAuthenticationCacheImpl.java
  src/main/src/main/java/org/geoserver/security/auth/UsernamePasswordAuthenticationProvider.java
  src/main/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest.java
  src/main/src/test/java/org/geoserver/security/auth/TestingAuthenticationCache.java
  src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
  src/security/security-tests/src/test/java/org/geoserver/security/auth/AbstractAuthenticationProviderTest-context.xml
Labels: backport 2.24.x, backport 2.25.x

#7795 Update Logging Statement for WMS Store Deletion
  src/restconfig/src/main/java/org/geoserver/rest/catalog/WMSStoreController.java
  src/restconfig/src/main/java/org/geoserver/rest/catalog/WMTSStoreController.java
Labels: backport 2.24.x, backport 2.25.x

#7798 GEOS-11484: mapWrapping/advProjectionHandler format_options supported by DirectRasterRenderer
  src/wms/src/main/java/org/geoserver/wms/map/DirectRasterRenderer.java
  src/wms/src/main/java/org/geoserver/wms/map/RenderedImageMapOutputFormat.java
  src/wms/src/test/java/org/geoserver/wms/map/RenderedImageMapOutputFormatTest.java
  src/wms/src/test/resources/org/geoserver/wms/map/direct-raster-expected.png
  src/wms/src/test/resources/org/geoserver/wms/map/direct-raster-format-options-expected.png
Labels: backport 2.24.x, backport 2.25.x
