Repository geoserver/geoserver, pull requests merged in 2025-01, with the labels that each got.

#8181 [GEOS-11671] Upgrade H3 dependency to 3.7.3
  src/community/ogcapi/dggs/dggs-core/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8190 [GEOS-11680] Azure COG assembly lacks mandatory libraries, won't work
  src/community/cog/cog-azure/src/assembly/assembly.xml
Labels: backport 2.26.x

#8193 [GEOS-11681] MapML raster GetFeatureInfo not working
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGenerator.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLGetFeatureInfoOutputFormat.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
Labels: backport 2.25.x, backport 2.26.x

#8200 [GEOS-11685] Bump jetty.version from 9.4.56.v20240826 to 9.4.57.v20241219
  src/pom.xml
Labels: dependencies, backport 2.25.x, backport 2.26.x

#8192 [GEOS-11682] Add tests for WMS SLD XML request reader
  src/wms/src/main/java/org/geoserver/sld/SLDXmlRequestReader.java
  src/wms/src/test/java/org/geoserver/sld/SLDXmlRequestReaderTest.java
Labels: backport 2.25.x, backport 2.26.x

#8206 [GEOS-11683] MapML WMS Features Coordinate Precision Should be adjusted based on scale
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLFeaturesBuilder.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLSimplifier.java
  src/extension/mapml/src/main/java/org/geoserver/mapml/RoundingPrecisionTransformer.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLStyleVisitorTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSFeatureTest.java
Labels: backport 2.25.x, backport 2.26.x

#8218 [GEOS-11689] IOUtilsTest should not ping an external web site
  src/rest/src/test/java/org/geoserver/rest/util/IOUtilsTest.java
Labels: backport 2.25.x, backport 2.26.x

#8219 [GEOS-11672] WMTS layer service enablement
  src/gwc/src/main/java/org/geoserver/gwc/wmts/GWCResourceServiceVoter.java
  src/web/core/src/main/java/org/geoserver/web/ServiceDescriptionProvider.java
  src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
  src/web/gwc/src/test/java/org/geoserver/gwc/web/GWCServiceLinksTest.java
  src/web/wcs/src/main/java/org/geoserver/wcs/web/WCSServiceDescriptionProvider.java
  src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSServiceDescriptionProvider.java
Labels: backport 2.25.x, backport 2.26.x

#8232 [GEOS-11694] OpenID connect: allow caching authentication when an expiration is declared in the access token
  doc/en/user/source/community/oauth2/oidc.rst
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectFilterConfig.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/test/java/org/geoserver/security/oauth2/OpenIdConnectIntegrationTest.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.html
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanel.java
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/main/resources/GeoServerApplication.properties
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-web/src/test/java/org/geoserver/web/security/oauth2/OpenIdConnectAuthProviderPanelTest.java
  src/community/security/oauth2/oauth2-core/src/main/java/org/geoserver/security/oauth2/GeoServerOAuthAuthenticationFilter.java
  src/main/src/main/java/org/geoserver/security/filter/GeoServerSecurityFilter.java
Labels: backport 2.25.x, backport 2.26.x

#8240 Replace google-java-format by palantir in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: backport 2.25.x, backport 2.26.x

#8239 [GEOS-10844] Exclude xml-apis from build
  src/extension/printing/pom.xml
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8246 [GEOS-11701] Update JAI-Ext to 1.1.28
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8245 Update Tomcat recommendation, update external links
  doc/en/user/source/installation/war.rst
Labels: backport 2.26.x
