Repository geoserver/geoserver, pull requests merged in 2025-05, with the labels that each got.

#8506 [GEOS-11801] MapML preview link zoom and extent are incorrect
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLDocumentBuilder.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
Labels: backport 2.26.x, backport 2.27.x

#8518 [GEOS-11811] Fix features templating editor unable to save content
  src/community/features-templating/features-templating-web/src/main/java/org/geoserver/featurestemplating/web/TemplateConfigurationPage.java
Labels: backport 2.25.x, backport 2.26.x, backport 2.27.x

#8525 [GEOS-11816] Features templating OGC API fetch by ID fails
  src/community/features-templating/features-templating-ogcapi/src/main/java/org/geoserver/featurestemplating/ogcapi/TemplateCallBackOGC.java
  src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/GMLComplexFeatureResponseAPITest.java
Labels: backport 2.27.x

#8513 [GEOS-11810] New application setting to allow access by Workspace Admin
  doc/en/user/source/configuration/properties/index.rst
  doc/en/user/source/data/webadmin/workspaces.rst
  src/web/core/src/main/java/org/geoserver/web/data/workspace/WorkspaceEditPage.java
  src/web/core/src/main/java/org/geoserver/web/services/BaseServiceAdminPage.java
  src/web/wfs/src/test/java/org/geoserver/wfs/web/WFSAdminPageTest.java
Labels: backport 2.26.x, backport 2.27.x

#8524 [GEOS-11817] GUI spinner remains after drag and drop
  src/extension/geofence/geofence-server/src/main/java/org/geoserver/geofence/server/web/GeofenceServerAdminPage.java
  src/extension/geofence/geofence-server/src/main/java/org/geoserver/geofence/server/web/GeofenceServerPage.java
  src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerDNDBehavior.java
  src/web/core/src/main/java/org/geoserver/web/wicket/ReorderableTablePanel.java
  src/web/core/src/main/java/org/geoserver/web/wicket/gs-wicket-dnd.js
  src/web/core/src/test/java/org/geoserver/web/data/layergroup/LayerGroupEditPageTest.java
Labels: backport 2.27.x

#8519 [GEOS-11812] Smart data loader cyclic dependency exception fixes
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/data/store/NestedTreeDomainModelVisitor.java
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/IndexedDomainModelVisitor.java
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/IndexedDomainModelVisitorImpl.java
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/entities/DomainRelation.java
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/visitors/appschema/AppSchemaVisitor.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/domain/DomainModelBuilderCyclicTest.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/postgis/MeteoStationsPostGISTestSetUp.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/postgis/PostgisCyclicAppSchemaVisitorTest.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/postgis/PostgisDomainModelBuilderCyclicTest.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/visitors/JDBCCyclicAppSchemaVisitorTest.java
  src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_db_cyclic.sql
  src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/visitors/meteo-stations-appschema-cyclic.xml
Labels: backport 2.26.x, backport 2.27.x

#8527 [GEOS-11818] PageUniqueProcess regression after [GEOT-7628]
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSTestSupport.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/H2PagedUniqueTest.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/PagedUniqueProcessTest.java
Labels: backport 2.26.x, backport 2.27.x

#8548 GEOS-11831: oseo callback improvements
  src/community/oseo/oseo-service/src/main/java/org/geoserver/opensearch/eo/OSEODispatcherCallback.java
  src/community/oseo/oseo-service/src/test/java/org/geoserver/opensearch/eo/SearchTest.java
Labels: backport 2.26.x, backport 2.27.x

#8555 [GEOS-11834] Update PMD to 7.13
  build/qa/pmd-junit-ruleset.xml
  src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseGeometrylessOnlineTest.java
  src/community/ogcapi/dggs/dggs-clickhouse/src/test/java/org/geotools/dggs/clickhouse/ClickHouseRHealPixOnlineTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
  src/pom.xml
Labels: backport 2.26.x, backport 2.27.x

#8551 [GEOS-11832] count=0 service exception for some formats
  src/wfs/src/main/java/org/geoserver/wfs/GetFeature.java
  src/wfs/src/test/java/org/geoserver/wfs/response/CSVOutputFormatTest.java
  src/wfs/src/test/java/org/geoserver/wfs/response/GeoJsonOutputFormatTest.java
  src/wfs/src/test/java/org/geoserver/wfs/response/ShapeZipTest.java
  src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeaturePagingTest.java
Labels: backport 2.26.x, backport 2.27.x

#8546 [GEOS-11830] Smart data loader create store page fails when environment variables are in use
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/data/store/panel/SmartDataLoaderStoreEditPanel.java
Labels: backport 2.26.x, backport 2.27.x

#8568 [GEOS-11843] Use Spring framework BOM to manage Spring and Spring Security dependencies
  doc/en/developer/source/maven-guide/index.rst
  doc/en/developer/source/policies/community-modules.rst
  src/community/backup-restore/core/pom.xml
  src/community/jms-cluster/activemqBroker/pom.xml
  src/community/taskmanager/core/bin/pom.xml
  src/community/taskmanager/core/pom.xml
  src/extension/security/cas/pom.xml
  src/main/pom.xml
  src/pom.xml
  src/rest/pom.xml
  src/restconfig/pom.xml
  src/security/ldap/pom.xml
  src/web/security/ldap/pom.xml
  src/wms/pom.xml
Labels: dependencies

#8566 [GEOS-11839]: WPS download NetCDF output format
  doc/en/user/source/community/index.rst
  doc/en/user/source/community/netcdf-ghrsst/index.rst
  doc/en/user/source/community/wps-download-netcdf/index.rst
  doc/en/user/source/extensions/netcdf-out/index.rst
  src/community/pom.xml
  src/community/wps-download-netcdf/pom.xml
  src/community/wps-download-netcdf/src/assembly/assembly.xml
  src/community/wps-download-netcdf/src/main/java/applicationContext.xml
  src/community/wps-download-netcdf/src/main/java/org/geoserver/wps/ppio/BaseNetCDFPPIO.java
  src/community/wps-download-netcdf/src/test/java/org/geoserver/wps/ppio/NetCDFDownloadProcessTest.java
  src/extension/netcdf-out/src/main/java/org/geoserver/wcs/responses/AbstractNetCDFEncoder.java
  src/extension/netcdf-out/src/main/java/org/geoserver/web/netcdf/layer/NetCDFLayerSettingsContainer.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadEstimatorProcess.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownload.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterDownloadContext.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/RasterEstimator.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/SpatioTemporalCoverageSlicer.java
  src/extension/wps-download/src/main/resources/applicationContext.xml
  src/extension/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSTestSupport.java
  src/main/src/test/java/org/geoserver/data/test/watertemp2.zip
  src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
  src/web/app/pom.xml
Labels: backport 2.26.x, backport 2.27.x
