Repository geoserver/geoserver, pull requests merged in 2025-07, with the labels that each got.

#8644 [GEOS-11880] OGC API Maps is not showing up in GeoServer home page
  src/community/ogcapi/ogcapi-maps-assembly/pom.xml
Labels: backport 2.26.x, backport 2.27.x

#8638 GEOS-11876: WPS Longitudinal profile optional distance
  doc/en/user/source/community/wps-longitudinal-profile/index.rst
  src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/DistanceSlopeCalculator.java
  src/community/wps-longitudinal-profile/src/main/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcess.java
  src/community/wps-longitudinal-profile/src/test/java/org/geoserver/wps/longitudinal/LongitudinalProfileProcessTest.java
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/EWKTPPIO.java
  src/main/src/test/java/org/geoserver/data/test/dem.zip
Labels: backport 2.26.x, backport 2.27.x

#8647 [GEOS-11882] Cleanup postgis-jdbc dependencies
  src/web/app/pom.xml
Labels: dependencies, backport 2.27.x

#8642 [GEOS-11878] WFS HITS request returns the whole data records on a GML feature templated layer
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/TemplateCallback.java
  src/community/features-templating/features-templating-ows/src/test/java/org/geoserver/featurestemplating/response/GML3GetComplexFeatureTest.java
Labels: backport 2.26.x, backport 2.27.x

#8643 [GEOS-11879] Xalan causes a java.lang.NoClassDefFoundError
  src/extension/printing/pom.xml
Labels: dependencies, backport 2.27.x

#8669 Bump GeoFence to 3.8.1
  src/pom.xml
Labels: dependencies, backport 2.27.x

#8670 [GEOS-11887] Features Templating does not returns content type and charset header on OGC-API
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateComplexTestSupport.java
  src/community/features-templating/features-templating-core/src/test/java/org/geoserver/featurestemplating/response/TemplateJSONSimpleTestSupport.java
  src/community/features-templating/features-templating-ogcapi/src/test/java/org/geoserver/featurestemplating/response/GMLComplexFeatureResponseAPITest.java
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/BaseTemplateGetFeatureResponse.java
  src/community/features-templating/features-templating-ows/src/main/java/org/geoserver/featurestemplating/ows/wfs/GMLTemplateResponse.java
  src/extension/ogcapi/ogcapi-core/src/main/java/org/geoserver/ogcapi/APIBodyMethodProcessor.java
  src/extension/ogcapi/ogcapi-features/src/test/java/org/geoserver/ogcapi/v1/features/FeatureTest.java
Labels: backport 2.26.x, backport 2.27.x

#8664 [GEOS-11885] Add UUID support on SmartDataLoader
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/domain/DomainModelBuilder.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/domain/DomainModelBuilderTest.java
  src/community/smart-data-loader/src/test/resources/org/geoserver/smartdataloader/postgis/mockdata/meteo_int8_db.sql
Labels: backport 2.26.x, backport 2.27.x

#8689 Fix deprecation warnings due to upstream commons-lang3 upgrade
  src/extension/importer/core/src/main/java/org/geoserver/importer/transform/AttributesToPointGeometryTransform.java
  src/extension/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadAnimationProcess.java
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/executor/ProcessListenerNotifier.java
  src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
  src/main/src/main/java/org/geoserver/security/DisabledServiceResourceFilter.java
  src/platform/src/main/java/org/geoserver/platform/resource/Resources.java
  src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPRoleService.java
  src/security/ldap/src/main/java/org/geoserver/security/ldap/LDAPUserGroupService.java
Labels: dependencies
