Repository geoserver/geoserver, pull requests merged in 2025-03, with the labels that each got.

#8364 [GEOS-11743] Upgrade Oracle JDBC driver (ojdbc) from 8 to 11
  src/community/jdbcconfig/pom.xml
  src/extension/app-schema/app-schema-oracle-test/pom.xml
  src/extension/app-schema/app-schema-test/pom.xml
  src/extension/oracle/pom.xml
  src/extension/wps-jdbc/pom.xml
  src/pom.xml
  src/release/ext-oracle.xml
  src/release/extensions/oracle/oracle-README.md
  src/web/app/pom.xml
Labels: dependencies, backport 2.26.x

#8362 Re-enable sec-jdbc module's JNDI tests without requiring jndi.properties file
  src/security/jdbc/pom.xml
  src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDIRoleServiceTest.java
  src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDITestConfig.java
  src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDIUserDetailsServiceTest.java
  src/security/jdbc/src/test/java/org/geoserver/security/jdbc/H2JNDIUserGroupServiceTest.java
  src/security/jdbc/src/test/resources/jndi.properties
Labels: backport 2.26.x

#8384 [GEOS-11757] Optimize ConfigurationPasswordEncryptionHelper to cache encrypted fields by store type
  src/main/src/main/java/org/geoserver/security/password/ConfigurationPasswordEncryptionHelper.java
  src/main/src/test/java/org/geoserver/security/password/ConfigurationPasswordEncryptionHelperTest.java
Labels: backport 2.26.x

#8380 Make StatusPageTest.ExtraTabDefinition serializable
  src/web/core/src/test/java/org/geoserver/web/admin/StatusPageTest.java
Labels: backport 2.26.x

#8345 [GEOS-11725] Environment parameters resolving is not working on Smart data loader
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/data/SmartDataLoaderDataAccessFactory.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/AbstractJDBCSmartDataLoaderTestSupport.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/data/store/EnvParametrizationStoreTest.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/postgis/PostGisEnvParametrizationStoreTest.java
Labels: backport 2.25.x, backport 2.26.x

#8382 [GEOS-11755] AbstractCatalogFacade leaves dangling references to temporary Catalog
  src/main/src/main/java/org/geoserver/catalog/impl/AbstractCatalogFacade.java
  src/main/src/test/java/org/geoserver/catalog/impl/CatalogImplTest.java
Labels: backport 2.26.x

#8376 [GEOS-11760] Fix a potential OOM in the KML transformation
  src/kml/src/main/java/org/geoserver/kml/KMLEncoder.java
  src/kml/src/main/resources/org/geoserver/kml/icon_style_patch.xsl
  src/kml/src/test/java/org/geoserver/kml/KMLReflectorTest.java
Labels: backport 2.25.x, backport 2.26.x

#8399 [GEOS-11763] Update jai-ext to latest version (1.1.30)
  src/pom.xml
Labels: dependencies, backport 2.26.x

#8395 [GEOS-11761] Add support for the clip vendor parameter to WCS as well
  doc/en/user/source/services/wcs/vendor.rst
  doc/en/user/source/services/wms/vendor.rst
  src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSNetCDFMosaicTest.java
  src/main/src/main/java/org/geoserver/ows/kvp/ClipGeometryParser.java
  src/wcs/src/main/java/applicationContext.xml
  src/wcs/src/main/java/org/geoserver/wcs/WCSCoverageClipCallback.java
  src/wcs/src/main/java/org/vfny/geoserver/util/WCSUtils.java
  src/wcs2_0/src/main/java/applicationContext.xml
  src/wcs2_0/src/main/java/org/geoserver/wcs2_0/GranuleStackClipCallback.java
  src/wcs2_0/src/test/java/org/geoserver/wcs2_0/kvp/GetCoverageKvpTest.java
  src/wms/src/main/java/org/geoserver/wms/clip/ClipWMSGetMapCallBack.java
Labels: backport 2.26.x

#8398 [GEOS-11762] Templates can not be listed via GeoServer Rest API
  src/community/features-templating/features-templating-rest/src/main/java/org/geoserver/featurestemplating/rest/TemplateRestController.java
  src/community/features-templating/features-templating-rest/src/test/java/org/geoserver/featurestemplating/rest/TemplateRestControllerTest.java
Labels: backport 2.25.x, backport 2.26.x

#8414 [GEOS-11769] Race conditions in LayerGroupHelper when the default catalog is not fully initialized
  src/main/src/main/java/org/geoserver/catalog/CatalogBuilder.java
  src/main/src/main/java/org/geoserver/catalog/LayerGroupHelper.java
  src/main/src/main/java/org/geoserver/catalog/impl/CatalogImpl.java
  src/main/src/test/java/org/geoserver/catalog/LayerGroupHelperTest.java
Labels: backport 2.26.x

#8417 [GEOS-11771] Update to Imageio-EXT 1.4.15
  src/pom.xml
Labels: backport 2.26.x

#8408 [GEOS-11767] Regression: OL preview always uses JPEG format
  src/wms/src/main/resources/webresources/wms/OpenLayers2Map.js
  src/wms/src/main/resources/webresources/wms/OpenLayers3Map.js
Labels: backport 2.25.x, backport 2.26.x

#8368 GEOS-11726: slow post requests: caching improvements
  src/community/jdbcconfig/src/main/java/org/geoserver/jdbcconfig/catalog/JDBCCatalogFacade.java
  src/main/src/main/java/org/geoserver/security/impl/DefaultResourceAccessManager.java
  src/main/src/test/java/org/geoserver/security/impl/DefaultResourceAccessManagerTest.java
  src/wfs/src/main/java/org/geoserver/wfs/xml/WFSXmlUtils.java
  src/wfs/src/test/java/org/geoserver/wfs/v2_0/GetFeatureTest.java
Labels: backport 2.26.x

#8447 GeoFence: use release version 3.8.0
  src/pom.xml
Labels: dependencies

#8426 [GEOS-11774] Logout with OAuth plugin will give error if logged in locally
  src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/src/main/java/org/geoserver/security/oauth2/OpenIdConnectAuthenticationFilter.java
Labels: backport 2.25.x, backport 2.26.x

#8450 GEOS-11791: REST controller logging details after validation
  src/restconfig/src/main/java/org/geoserver/rest/catalog/LayerGroupController.java
  src/restconfig/src/main/java/org/geoserver/rest/catalog/StyleController.java
  src/restconfig/src/main/java/org/geoserver/rest/catalog/WMSLayerController.java
  src/restconfig/src/main/java/org/geoserver/rest/catalog/WMTSLayerController.java
  src/restconfig/src/main/java/org/geoserver/rest/resources/ResourceController.java
Labels: backport 2.26.x
