Repository geoserver/geoserver, pull requests merged in 2025-06, with the labels that each got.

#8586 Upgrade postgresql from 42.7.5 to 42.7.6
  src/pom.xml
Labels: dependencies, backport 2.27.x

#8587 Upgrade commons-beanutils from 1.10.1 to 1.11.0
  src/pom.xml
Labels: dependencies, backport 2.26.x, backport 2.27.x

#8592 Upgrade commons-io from 2.18.0 to 2.19.0
  src/pom.xml
Labels: dependencies, backport 2.27.x

#8547 [GEOS-11820] - WCS spatial sub-setting does not work when native CRS != declared CRS
  src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MSG_Europe_IR120_202412061315-geotiff.zip
  src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/WCSMultiDimSubsetTest.java
  src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/World_mosaic.zip
  src/wcs2_0/src/main/java/org/geoserver/wcs2_0/response/WCSDimensionsSubsetHelper.java
Labels: backport 2.26.x, backport 2.27.x

#8611 [GEOS-11862] Layer Preview and Tile Layers page dropdown links broken after updating table
  src/web/core/src/main/java/org/geoserver/web/wicket/GeoServerTablePanel.java
  src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.html
  src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.java
  src/web/demo/src/main/java/org/geoserver/web/demo/MapPreviewPage.js
  src/web/demo/src/test/java/org/geoserver/web/demo/MapPreviewPageTest.java
  src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.java
  src/web/gwc/src/main/java/org/geoserver/gwc/web/layer/CachedLayersPage.js
  src/web/gwc/src/test/java/org/geoserver/gwc/web/layer/CachedLayersPageTest.java
Labels: backport 2.27.x
