Repository geoserver/geoserver, pull requests merged in 2025-02, with the labels that each got.

#8231 [GEOS-11696] AdminRequestCallback not loaded due to spring bean name conflict
  src/community/acl/src/test/java/org/geoserver/acl/plugin/integration/AclContainerIntegrationTest.java
  src/extension/sldService/src/test/java/org/geoserver/sldservice/rest/RasterizerTest.java
  src/extension/sldService/src/test/java/sldservice-applicationContext.xml
  src/main/src/test/java/org/geoserver/test/GeoServerSystemTestSupport.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/AdminRequestTest.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/CatalogRESTTestSupport.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/TemplateControllerTest.java
  src/web/app/src/test/java/org/geoserver/web/AdminRequestCallbackTest.java
  src/web/core/src/main/java/applicationContext.xml
Labels: backport 2.25.x, backport 2.26.x

#8257 [GEOS-11703] HEAD and OPTIONS requests on the REST API return a 403
  data/release/security/rest.properties
  src/main/src/main/java/org/geoserver/security/RESTfulDefinitionSource.java
  src/main/src/main/java/org/geoserver/security/impl/RESTAccessRuleDAO.java
  src/main/src/main/java/org/geoserver/security/impl/rest.properties.template
  src/main/src/test/java/org/geoserver/data/test/security.zip
  src/restconfig/src/main/java/org/geoserver/rest/security/RestAccessController.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/AboutStatusControllerTest.java
  src/restconfig/src/test/java/org/geoserver/rest/catalog/SecuredControllerAccessTest.java
  src/restconfig/src/test/java/org/geoserver/rest/security/AccessControllersTest.java
Labels: backport 2.25.x, backport 2.26.x

#8267 [GEOS-11713] Concurrent LDAP builds fail on Jenkins
  src/security/ldap/pom.xml
  src/web/security/ldap/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8264 [Backport 2.26.x][GEOS-11666] Update MapML viewer to latest release 0.16.0
  doc/en/user/source/extensions/mapml/installation.rst
  doc/en/user/source/extensions/mapml/template.rst
  src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLHTMLOutput.java
  src/extension/mapml/src/main/resources/viewer/widget/layer.js
  src/extension/mapml/src/main/resources/viewer/widget/leaflet.js
  src/extension/mapml/src/main/resources/viewer/widget/map-caption.js
  src/extension/mapml/src/main/resources/viewer/widget/map-extent.js
  src/extension/mapml/src/main/resources/viewer/widget/map-feature.js
  src/extension/mapml/src/main/resources/viewer/widget/map-input.js
  src/extension/mapml/src/main/resources/viewer/widget/map-link.js
  src/extension/mapml/src/main/resources/viewer/widget/map-select.js
  src/extension/mapml/src/main/resources/viewer/widget/map-style.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml-viewer.js
  src/extension/mapml/src/main/resources/viewer/widget/mapml.css
  src/extension/mapml/src/main/resources/viewer/widget/mapml.js
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLHTMLGetFeatureTest.java
  src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java
Labels: backport 2.25.x

#8276 Upgrade commons-lang3 from 3.15.0 to 3.17.0
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8273 Upgrade commons-io from 2.16.1 to 2.18.0
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8271 Upgrade guava from 33.2.1 to 33.4.0
  src/extension/vectortiles/src/main/java/org/geoserver/wms/geojson/GeoJsonWMSBuilder.java
  src/extension/vectortiles/src/main/java/org/geoserver/wms/topojson/TopologyBuilder.java
  src/pom.xml
  src/web/demo/src/main/java/org/geoserver/web/demo/DemoRequestsPage.java
Labels: backport 2.25.x, backport 2.26.x

#8259 [GEOS-11706] fix WCS Request panel - get CRS details (both)
  src/web/core/src/main/java/org/geoserver/web/wicket/CRSPanel.java
  src/web/core/src/main/java/org/geoserver/web/wicket/EnvelopePanel.java
  src/web/wcs/src/main/java/org/geoserver/wcs/web/demo/WCSRequestBuilderPanel.java
Labels: backport 2.26.x

#8289 Upgrade jsoup from 1.18.1 to 1.18.3
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8290 Upgrade commons-lang from 2.5 to 2.6
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8285 Upgrade easymock from 5.4.0 to 5.5.0
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8286 Upgrade mockito from 5.12.0 to 5.15.2
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8287 [GEOS-11715] STAC sortby won't work with properties. prefixed names
  src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/v1/stac/STACSortablesMapper.java
  src/community/oseo/oseo-stac/src/test/java/org/geoserver/ogcapi/v1/stac/SearchTest.java
Labels: backport 2.25.x, backport 2.26.x

#8305 Upgrade oshi-core from 6.6.3 to 6.6.6
  src/pom.xml
Labels: dependencies, backport 2.25.x, backport 2.26.x

#8304 Upgrade wiremock from 3.10.0 to 3.11.0
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8302 Upgrade commons-text from 1.12.0 to 1.13.0
  src/pom.xml
Labels: backport 2.25.x, backport 2.26.x

#8249 [GEOS-11700] GeoFence fails in recognizing some caller IP address
  src/extension/geofence/geofence/src/main/java/org/geoserver/geofence/GeofenceAccessManager.java
  src/extension/geofence/geofence/src/test/java/org/geoserver/geofence/GeofenceAccessManagerTest.java
Labels: backport 2.24.x, backport 2.25.x, backport 2.26.x

#8317 Upgrade junit-upiter from 5.10.1 to 5.11.4
  src/pom.xml
Labels: backport 2.26.x

#8313 Upgrade commons-logging from 1.2 to 1.3.5
  src/pom.xml
Labels: backport 2.26.x

#8312 Upgrade commons-beanutils from 1.9.4 to 1.10.1
  src/pom.xml
Labels: dependencies, backport 2.26.x

#8303 Upgrade hazelcast from 5.3.6 to 5.3.8
  src/pom.xml
Labels: dependencies, backport 2.26.x

#8331 Upgrading JAI-EXT to 1.1.29
  src/pom.xml
Labels: dependencies, backport 2.26.x

#8307 Enforce Maven 3.8+ for improved plugin version resolution
  src/pom.xml
Labels: backport 2.26.x

#8359 [GEOS-11620] Fix JDBC URL parsing issue on Smart data loader
  src/community/smart-data-loader/src/main/java/org/geoserver/smartdataloader/metadata/jdbc/utils/JdbcUrlSplitter.java
  src/community/smart-data-loader/src/test/java/org/geoserver/smartdataloader/metadata/jdbc/utils/JdbcUrlSplitterTest.java
Labels: backport 2.25.x, backport 2.26.x
