Repository geoserver/geoserver, pull requests merged in 2025-04, with the labels that each got.

#8455 [GEOS-11792] Fix welcome page listing all services via sevice caps
  src/extension/csw/web-csw/src/main/java/org/geoserver/csw/web/CSWServiceDescriptionProvider.java
  src/extension/ogcapi/web-ogcapi/src/main/java/org/geoserver/web/ogcapi/OgcApiServiceDescriptionProvider.java
  src/extension/ogcapi/web-ogcapi/src/test/java/org/geoserver/web/ogcapi/OgcApiServiceDescriptionProviderTest.java
  src/extension/wps/web-wps/src/main/java/org/geoserver/wps/web/WPSServiceDescriptionProvider.java
  src/main/src/main/java/org/geoserver/ows/DisabledServiceCheck.java
  src/web/core/src/main/java/org/geoserver/web/ServiceDescriptionProvider.java
  src/web/core/src/main/java/org/geoserver/web/ServiceInfoCapabilitiesProvider.java
  src/web/core/src/test/java/org/geoserver/web/CapabilitiesHomePagePanelTest.java
  src/web/core/src/test/java/org/geoserver/web/FakeServiceDescriptionProvider.java
  src/web/core/src/test/resources/applicationContext.xml
  src/web/gwc/src/main/java/org/geoserver/gwc/web/GWCServiceDescriptionProvider.java
  src/web/rest/src/main/java/org/geoserver/web/RESTServiceDescriptionProvider.java
  src/web/wcs/src/main/java/org/geoserver/wcs/web/WCSServiceDescriptionProvider.java
  src/web/wfs/src/main/java/org/geoserver/wfs/web/WFSServiceDescriptionProvider.java
  src/web/wms/src/main/java/org/geoserver/wms/web/WMSServiceDescriptionProvider.java
Labels: backport 2.26.x

#8465 [GEOS-11796] Deadlocks During GeoServer Startup When Loading Style Group Layer Groups
  src/main/src/main/java/org/geoserver/config/GeoServerDataDirectory.java
  src/main/src/main/java/org/geoserver/config/datadir/CatalogLoader.java
  src/main/src/main/java/org/geoserver/config/datadir/DataDirectoryGeoServerLoader.java
  src/main/src/test/java/org/geoserver/config/datadir/MinimalConfigLoaderSupportIntegrationTest.java
  src/main/src/test/resources/data_dir/nested_layer_groups/styles/namedstyle.sld
  src/main/src/test/resources/data_dir/nested_layer_groups/styles/namedstyle.xml
Labels: backport 2.27.x

#8466 README.html user forum update
  src/release/src/markdown/README.md
Labels: backport 2.26.x, backport 2.27.x

#8459 [GEOS-11274,GEOS-11751] Generate URL for graphic inside workspace
  src/kml/src/main/java/org/geoserver/kml/decorator/PlacemarkStyleDecoratorFactory.java
  src/wms/src/main/java/org/geoserver/wms/icons/IconProperties.java
  src/wms/src/main/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicBuilder.java
  src/wms/src/test/java/org/geoserver/wms/icons/IconPropertiesTest.java
  src/wms/src/test/java/org/geoserver/wms/legendgraphic/JSONLegendGraphicOutputFormatTest.java
  src/wms/src/test/resources/org/geoserver/wms/legendgraphic/arealandmarks.sld
Labels: backport 2.26.x, backport 2.27.x

#8462 [GEOS-11795] Incorrect clipping of point geometries in vector tiles
  src/extension/vectortiles/src/main/java/no/ecc/vectortile/VectorTileEncoderNoClip.java
  src/extension/vectortiles/src/test/java/org/geoserver/wms/vector/VectorTileEncoderNoClipTest.java
Labels: backport 2.26.x, backport 2.27.x

#8476 [GEOS-11797]: Add support for Jiffle expressions in coverage view setup
  doc/en/user/source/data/raster/coverageview.rst
  doc/en/user/source/data/raster/images/coverageview3bandsdetails.png
  doc/en/user/source/data/raster/images/coverageview3bandsout.png
  doc/en/user/source/data/raster/images/coverageviewbandselect.png
  doc/en/user/source/data/raster/images/coverageviewjiffleselect.png
  doc/en/user/source/data/raster/images/coverageviewndvidetails.png
  doc/en/user/source/data/raster/images/coverageviewndvijiffle.png
  doc/en/user/source/data/raster/images/coverageviewsentinelbands.png
  doc/en/user/source/data/raster/images/coverageviewworldbands.png
  doc/en/user/source/data/raster/images/newcoverageview.png
  src/main/pom.xml
  src/main/src/main/java/org/geoserver/catalog/CoverageDimensionCustomizerReader.java
  src/main/src/main/java/org/geoserver/catalog/CoverageView.java
  src/main/src/main/java/org/geoserver/catalog/CoverageViewHandler.java
  src/main/src/main/java/org/geoserver/catalog/CoverageViewReader.java
  src/main/src/main/java/org/geoserver/catalog/JiffleParser.java
  src/main/src/test/java/org/geoserver/catalog/CoverageViewTest.java
  src/pom.xml
  src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewAbstractPage.java
  src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.html
  src/web/core/src/main/java/org/geoserver/web/data/layer/CoverageViewEditor.java
  src/web/core/src/main/resources/GeoServerApplication.properties
  src/web/core/src/test/java/org/geoserver/web/data/layer/CoverageViewEditorTest.java
Labels: backport 2.26.x, backport 2.27.x

#8472 [GEOS-11793] WPS Read Value from Coverage Position
  src/extension/wps/wps-core/src/main/java/applicationContext.xml
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/GetCoveragesValue.java
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/ppio/ValuesAtPointPPIO.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/WPSTestSupport.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/GetCoveragesValueTest.java
  src/main/src/test/java/org/geoserver/data/test/MockData.java
  src/main/src/test/java/org/geoserver/data/test/elshaped.zip
  src/main/src/test/java/org/geoserver/data/test/hole.zip
  src/main/src/test/java/org/geoserver/data/test/tazdemNoData2.tiff
Labels: backport 2.26.x, backport 2.27.x

#8485 Documentation for the hz-clustering community module
  doc/en/user/source/community/hz-cluster/index.rst
  doc/en/user/source/community/index.rst
Labels: backport 2.26.x, backport 2.27.x

#8491 [GEOS-11800]: Spatiotemporal Zonal Statistics WPS process
  src/extension/wps/wps-core/src/main/java/applicationContext.xml
  src/extension/wps/wps-core/src/main/java/org/geoserver/wps/gs/SpatioTemporalZonalStatistics.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/SpatioTemporalStatisticsTests.java
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/temperatures.zip
  src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/zones.properties
Labels: backport 2.26.x, backport 2.27.x

#8503 [GEOS-11802] Add GeoParquet DataStore community module
  src/community/geoparquet/README.md
  src/community/geoparquet/pom.xml
  src/community/geoparquet/src/assembly/assembly.xml
  src/community/geoparquet/src/main/java/org/geoserver/web/data/store/geoparquet/GeoParquetDataStoreEditPanel.html
  src/community/geoparquet/src/main/java/org/geoserver/web/data/store/geoparquet/GeoParquetDataStoreEditPanel.java
  src/community/geoparquet/src/main/java/org/geoserver/web/data/store/geoparquet/package-info.java
  src/community/geoparquet/src/main/java/org/geoserver/web/wicket/form/ConverterModel.java
  src/community/geoparquet/src/main/java/org/geoserver/web/wicket/form/NumberParamPanel.html
  src/community/geoparquet/src/main/java/org/geoserver/web/wicket/form/NumberParamPanel.java
  src/community/geoparquet/src/main/java/org/geoserver/web/wicket/form/URIParamPanel.html
  src/community/geoparquet/src/main/java/org/geoserver/web/wicket/form/URIParamPanel.java
  src/community/geoparquet/src/main/java/org/geoserver/web/wicket/form/URIValidator.java
  src/community/geoparquet/src/main/resources/GeoServerApplication.properties
  src/community/geoparquet/src/main/resources/applicationContext.xml
  src/community/geoparquet/src/main/resources/org/geoserver/web/data/store/geoparquet/geoparquet-icon.svg
  src/community/geoparquet/src/main/resources/org/geoserver/web/data/store/geoparquet/geoparquet-logo.svg
  src/community/geoparquet/src/test/java/org/geoserver/web/wicket/form/URIValidatorGlobPatternTest.java
  src/community/geoparquet/src/test/java/org/geoserver/web/wicket/form/URIValidatorTest.java
  src/community/pom.xml
  src/web/app/pom.xml
Labels: backport 2.27.x

#8504 Fix all app-schema modules including gs-main test jar with compile scope
  src/extension/app-schema/app-schema-core/pom.xml
  src/extension/app-schema/app-schema-geopkg-test/pom.xml
  src/extension/app-schema/app-schema-indexes-test/pom.xml
  src/extension/app-schema/app-schema-mongo-test/pom.xml
  src/extension/app-schema/app-schema-oracle-test/pom.xml
  src/extension/app-schema/app-schema-postgis-test/pom.xml
  src/extension/app-schema/app-schema-solr-test/pom.xml
  src/extension/app-schema/app-schema-test/pom.xml
  src/extension/app-schema/sample-data-access-test/pom.xml
Labels: backport 2.27.x
